### ISSUE TITLE
Configuration Files

### ISSUE THREAD

**Issue by s-chtl** [mahmoodlab/CLAM#1]
Hi, 
Thank you for making public this implementation of your very nice paper. 

I just wanted to inform you that it seems that the configuration file clam.yaml is not located in the directory \docs.

Thanks again for your work. 
Best,

**Comment by fedshyvana** [comment]
Thanks for pointing out! I just added. 
Max

**Comment by s-chtl** [comment]
Perfect ! Thank you and thanks for the prompt reply.
