### ISSUE TITLE
Bad sensitivity in independent testing dataset

### ISSUE THREAD

**Issue by MohamedOmar2020** [mahmoodlab/CLAM#100]
Hello, thank you very much for sharing this resource.
I have a dataset of 77 (class 0: 27 slides/ class 1: 50 slides) cytology WSIs which I am using to train a model for binary class prediction. I divided the data into 50 slides for training, 19 for validation and 8 for testing (that is because i have another cohort for testing). The model seems to yield good AUC, accuracy, sensitivity and specificity in the training and validation datasets and to a lesser extent in the small testing dataset. When I test the model on a separate testing dataset of 50 slides (class 0: 18 slides / class 1: 32 slides), it seems that the model always favours the smaller class, predicting almost all the 18 slides correctly while misclassifying most of the slides in the bigger class.  
Any idea why this is happening and how to fix it? I tried both clam sb and mb small and big and also mil with the exact same behaviour. Also I tried disabling instant clustering and changing bag weight but without improvement. 
Thanks in advance.

**Comment by MohamedOmar2020** [comment]
Yeah the AUC is very good. As you suggested, I was able to improve the sensitivity and accuracy by changing the threshold to a lower number than 0.5. I did this on the evaluation matrix shown below. However, the other issue is that the heatmaps generation would depend on the default threshold I guess for identifying the top patches for each class label. Any idea how to change this in the create_heatmaps script? 

 
<img width="380" alt="Screenshot 2022-02-09 at 11 24 23 AM" src="https://user-images.githubusercontent.com/51274531/153244213-2981d0e9-378c-49e8-b953-80305128c99f.png">

**Comment by fedshyvana** [comment]
heatmap generation is based on attention scores over patches (before feeding it to the final classifier) - which is independent of classification/binarization/thresholding. If your goal is to identity top patches that contribute to the model's prediction in each slide you can simply run the script as is.

**Comment by MohamedOmar2020** [comment]
I am using clam mb since it is the model giving reasonable probability to the second class label (p_1 in the picture above). For some reason, clam sb always has p_0 > 0.90 for all slides
