### ISSUE TITLE
Regarding the Label of TCGA WSI (tumor tissue vs. normal tissue)

### ISSUE THREAD

**Issue by omniaalwazzan** [mahmoodlab/CLAM#101]
Thank you so much for providing the code.

I'm particularly interested in merging histopathological images and transcriptome data, therefore I came across your PORPOISE article and am very keen to try out the PORPOISE code.

As noted in the PORPOISE code, image segmentation would need the usage of the CLAM code, therefore I am currently running the CLAM code on images retrieved from the GDC portal, but I wondered from where you obtained the label for a single Whole Slide Image (tumor tissue vs. normal tissue). Could you please offer some advice? 

Thanks for your time,
Omnia

**Comment by fedshyvana** [comment]
When you add cases to cart, there's an option to download "sample sheet", which contains a field "Sample Type"

**Comment by omniaalwazzan** [comment]
Thanks a lot for your feedback.

It’s clear now
