### ISSUE TITLE
Replacing Attention Network

### ISSUE THREAD

**Issue by micdic** [mahmoodlab/CLAM#102]
Hi Max,
to improve my results (LGG glioma subtypes classification) obtained till now with this excellent framework 
i was thinking of experiment another attention model. 

Can you please give me some more details about the intuition behind the attention model you applied here?

I see in the model_clam.py this forward pass:

    def forward(self, x):
        a = self.attention_a(x)
        b = self.attention_b(x)
        A = a.mul(b)
        A = self.attention_c(A)

where attention_a = Linear + Tanh
and     attention_b = Linear + Sigmoid

Did you tested other attention mechanisms? 

Thanks in advance for your time.
Michele.

**Comment by fedshyvana** [comment]
I have not tried any other attention mechanism so let me know if you find anything interesting/improvements with other setups :)

**Comment by micdic** [comment]
Ok, but can you please give me some more details about the intuition behind the attention model you applied here?
Thanks.

**Comment by fedshyvana** [comment]
I believe it comes from the gating mechanism used in some old NLP paper according to the AMIL paper https://arxiv.org/pdf/1802.04712.pdf.
