### ISSUE TITLE
Custom ResNet vs Torchvision Resnet

### ISSUE THREAD

**Issue by GeorgeBatch** [mahmoodlab/CLAM#103]
Dear authors,

Thank you very much for releasing your code and continuing the work on improving both the code and the documentation!

Before posting this question I looked through the closed issues, but have not found this question. I am sorry in case it has been asked and I overlooked it.

I came across the difference between your [custom implementation of ResNet](https://github.com/mahmoodlab/CLAM/blob/master/models/resnet_custom.py) and the implementation in [torchvision.models](https://pytorch.org/vision/stable/_modules/torchvision/models/resnet.html). In the paper, you state that you use adaptive pooling after the third layer, but there are more differences if I understand the output of [torchsummary](https://github.com/sksq96/pytorch-summary) correctly (see screenshots for resnet18 and txt files for resnet50).
[resnet50_clam.txt](https://github.com/mahmoodlab/CLAM/files/8126801/resnet50_clam.txt)
[resnet50_pytorch.txt](https://github.com/mahmoodlab/CLAM/files/8126802/resnet50_pytorch.txt)

**Custom ResNet-18**

<img width="285" alt="resnet18_clam" src="https://user-images.githubusercontent.com/46561186/155382207-821e5ab2-8fa3-4fab-be1c-c4c4dece2f8b.png">

**Torchvision ResNet-18**
<img width="281" alt="resnet18_pytorch" src="https://user-images.githubusercontent.com/46561186/155382229-bd822e9d-a551-4f66-9321-e5892882f2d0.png">

Is there a simple explanation for the other modifications?

Many thanks,
George

**Comment by fedshyvana** [comment]
we use adaptive pooling after the third BLOCK (not layer). If I remember correctly, ResNet50 is organized into 4 Residual Blocks (see the definition of Bottleneck in the ResNet code). If you use all 4 blocks, you get a feature map that's 2048 dimensions, whereas we truncated the model after the 3rd block, yielding 1024 features after spatial pooling.

**Comment by GeorgeBatch** [comment]
Yes, I understand. I called it layer because that's the term used in the `forward` methods. I understand this change.
CLAM:
```python
    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)

        return x
```

Torchvision:
```python
def _forward_impl(self, x: Tensor) -> Tensor:
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x
```

 I had a closer look at the summary txt files [resnet50_clam.txt](https://github.com/mahmoodlab/CLAM/files/8126801/resnet50_clam.txt) and [resnet50_pytorch.txt
](https://github.com/mahmoodlab/CLAM/files/8126802/resnet50_pytorch.txt) and indeed there are no other differences. Sorry for the confusion.

What I did not understand is how the ResNet-18 that I get by using your code with `layers=[2, 2, 2, 2]` (instead of `layers=[3, 4, 6, 3]` for ResNet-50) is so different from its torchvision counterpart. The difference is not only in the truncated 4th block but in the number of channels throughout the network and the dimensions (see screenshots from the original question). There should be some difference in how the BasicBlock-s and the BottleneckBlock-s are combined into the ResNet_Baseline class in your implementation and into the ResNet class in the PyTorch implementation such that for ResNet-50 the outcomes are identical (except for the 4th block truncation), but for ResNet-18 - completely different.

This was the difference I was asking about. But since you only used ResNet-50, truncating the 4th block is the only change you made to the ResNet architecture.

**Comment by fedshyvana** [comment]
ResNet18 and 34 uses BasicBlock instead of BottleNeck - since I only use ResNet50, we don't have the BasicBlock class defined and you won't be able to define a ResNet18 that's equivalent to the official implementation thru our code.

**Comment by GeorgeBatch** [comment]
That makes total sense now. Thank you very much!

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch, have you created the BasicBlock class suitable for ResNet18 and ResNet34? If so, could you please share it with me? Thank you!

**Comment by GeorgeBatch** [comment]
Hi Bryan, I have not tried ResNet18 or ResNet34 with CLAM.  I think you can
use the implementation of the Basic block from PyTorch with some
modifications:
https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch, thank you for your reply. I've successfully implemented the Basic Block with some modifications. 

What I don't quite understand now is the reason why ResNet50 was modified from its original version

**Comment by GeorgeBatch** [comment]
@bryanwong17, if you mean truncating the model after the third block, I think the intuition was that the ImageNet dataset that ResNet50 was made for is more diverse/complex than the pathology datasets used in the paper. So a simpler extractor with fewer layers and fewer output features was more suitable for the task (and probably showed better results).

see the reply from @fedshyvana:
> we use adaptive pooling after the third BLOCK (not layer). If I remember correctly, ResNet50 is organized into 4 Residual Blocks (see the definition of Bottleneck in the ResNet code). If you use all 4 blocks, you get a feature map that's 2048 dimensions, whereas we truncated the model after the 3rd block, yielding 1024 features after spatial pooling.
