### ISSUE TITLE
level_dim 38912*40192 is likely too large for successful segmentation, aborting

### ISSUE THREAD

**Issue by ccxsun** [mahmoodlab/CLAM#106]
Hi！ When I want to run create_patch_fp.py to segment WSI (.tif) file, the command line outputs the following message.
"level_dim 38912*40192 is likely too large for successful segmentation, aborting"
Is there any way to solve it? 
thanks!

**Comment by fedshyvana** [comment]
Does that mean your WSI only has a single downsample?

**Comment by ccxsun** [comment]
yes, the .tif file only has a single downsample. Should I manually downsample the image before running the program?

**Comment by fedshyvana** [comment]
No I think you'll lose information that way (due to compression). Maybe try to convert it to a tiled, pyramidal tif first (basically generate some downsamples yourself)? I believe you can do that using https://imagemagick.org/script/download.php. There should be command like convert path_to_source_img -define tiff:tile-geometry=256x256 ‘ptif:target_path’ to tile your tifs.

**Comment by qidog** [comment]
Have you solved this problem?

**Comment by ccxsun** [comment]
> 

Yes. you can convert the .tif to pyramid .tif by using vips（https://www.libvips.org/install.html）.
There are some command lines that might help：
vips tiffsave input.tif output.tif —-compression jpeg —-tile —-pyramid
vips openslideload input.tif “output.tif[tile,compression=jpeg]”

**Comment by ccxsun** [comment]
> Have you solved this problem?

Yes. you can convert the .tif to pyramid .tif by using vips（[https://www.libvips.org/install.html）](https://www.libvips.org/install.html%EF%BC%89).
There are some command lines that might help：
vips tiffsave input.tif output.tif —-compression jpeg —-tile —-pyramid
vips openslideload input.tif “output.tif[tile,compression=jpeg]”

**Comment by qidog** [comment]
> > Have you solved this problem?
> 
> Yes. you can convert the .tif to pyramid .tif by using vips（[https://www.libvips.org/install.html）](https://www.libvips.org/install.html%EF%BC%89). There are some command lines that might help： vips tiffsave input.tif output.tif —-compression jpeg —-tile —-pyramid vips openslideload input.tif “output.tif[tile,compression=jpeg]”

Thanks for your help, I will try this method. ：)
