### ISSUE TITLE
The output file location is not as expected on the windows platform.

### ISSUE THREAD

**Issue by One-sixth** [mahmoodlab/CLAM#107]
Hello, this is a great repository.
I trying to run this repo on windows platform.
I found a small bug that caused the output file location to on an unexpected location.

This bug is because the Windows path separator is '\'.
To fix it just replace line 30 of the file "wsi_core/WholeSlideImage.py" .

from
```
self.name = ".".join(path.split("/")[-1].split('.')[:-1])
```
to
```
self.name = os.path.splitext(os.path.basename(path))[0]
```

**Comment by fedshyvana** [comment]
cool thanks! this might explain some of the issues that windows users have reported on here...
