### ISSUE TITLE
Does one slide have mutiple subtyping？

### ISSUE THREAD

**Issue by WxpHB** [mahmoodlab/CLAM#109]
Hi，thanks for your excellent work. I'm confused that does one slide have mutiple subtyping？In your demo"tumor _subtyping_dummy_clean.csv" file, a slide only corresponds to a subtyping. But, in practice, a slide may correspond to mutiple subtyping, such as ductal carcinoma in situ and invasive carcinoma.

**Comment by fedshyvana** [comment]
If you expect the same slide to have multiple subtypes then you should treat it as a multi-label problem and adjust the training labels/loss functions accordingly
