### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (20028x512 and 1024x512)

### ISSUE THREAD

**Issue by lbertelo01** [mahmoodlab/CLAM#111]
Hi, 

First of all, what a great repository, thanks for sharing! 

I am rather new at computer vision and image classification, but I was able to train models similar to the ones in this script https://github.com/AMLab-Amsterdam/AttentionDeepMIL/blob/master/model.py while using your scripts for data prep. 
However, now that I want to try out the CLAM_SB model, I get a RuntimeError. It seems to be caused by the first fully connected linear layer but I am not sure how to fix the issue.
Any thoughts?

**Comment by lbertelo01** [comment]
Hi, I am trying to train a binary classifier (tumor vs no tumor) on this dataset (https://www.bracs.icar.cnr.it/details/). 
I have done the segmentation and patching with the default parameters of your code and used this model (https://github.com/ozanciga/self-supervised-histopathology/releases/tag/tenpercent) for feature extraction. Now I want to put the features through the CLAM_SB for classification which is where I get the error. 

![image](https://user-images.githubusercontent.com/98480071/158535440-f1a0887e-1da9-477b-ac20-4d3e0baf6bb3.png)

**Comment by fedshyvana** [comment]
it doesn't look like you're passing in the correct tensor shape as input to your model. Can you verify what your input shape looks like in a given mini-batch?

**Comment by fedshyvana** [comment]
Can you provide me the input size in the mini-batch? aka what does the data look like before you call output = model(data).

**Comment by lbertelo01** [comment]
Not really how to provide that answer, any help or directions? (still getting to know the topic and code).

**Comment by lbertelo01** [comment]
Hi again, figured out that each of my .pt files (collection of extracted features from one wsi) had torch.size(N, 512). (N=number of patches).

By adjusting L in class Attn_Net_Gated to 512 (instead of 1024) and the dictionary in class CLAM_SB self.size_dict = {"small": [1024, 512, 256], "big": [1024, 512, 384]} to:
![image](https://user-images.githubusercontent.com/98480071/159660316-769201d6-4d54-4589-9bbd-494459f8f08a.png)

I am not getting the RuntimeError anymore. 
This is the output when currently running python main.py --task tumor_vs_binary:

![image](https://user-images.githubusercontent.com/98480071/159659852-29fc060a-901a-4236-a56c-3c7407dc601c.png)

Just wondering if this is the correct way of approaching this issue?

**Comment by fedshyvana** [comment]
Hi there, sorry for the late reply - yes it looks like you figured it out!

**Comment by lbertelo01** [comment]
And that looks ok to you to set D to 1? I am just not sure how to pass tensors through the model and what size each layer should have. 

Another option would be to make sure that the extracted features coming out of the pretrained ResNet model have size Nx1024 but not sure how to approach that at the moment.

Any suggestions are welcome!

**Comment by lbertelo01** [comment]
Yes it is the dimension of the last layer, that is my question but you are right. Is it then an option to set size_dict to [512,512,256]?

**Comment by lbertelo01** [comment]
Or should the dimensions always decrease through the different layers?
