### ISSUE TITLE
Is there patches' position information in features extracted by `extract_features_fp.py` ?

### ISSUE THREAD

**Issue by RuixiangZhao** [mahmoodlab/CLAM#112]
Hi, thanks for your excellent work.

I'm confused that is there patches' position information in features extracted by `extract_features_fp.py` ?
In my understanding, each patch is embedded in a 1024-dimensional vector by a pretrained ResNet50, one whole slide image is embedded as a 2D vector, whose shape is [n, 1024] (n is the number of patches in the WSI). So, does the order of 1024-dimensional vector in the 2D vector mean the position of patch in the WSI? (maybe, patch corresponding to the first vector is located in the upper left corner of the WSI.) How can I get patches' relative(or absolute) position information from these features?

Thanks!

**Comment by fedshyvana** [comment]
It's saved in the .h5 files (in the same folder as the .pt features)
