### ISSUE TITLE
create_heatmaps.py uses step_size = patch_size irrespective of overlap parameter

### ISSUE THREAD

**Issue by KarthikNair1** [mahmoodlab/CLAM#113]
I have patch_size = 512 and overlap = 0.5, so I would have expected step_size = 256. However, from inspecting the coordinates, the step_size is 512. Digging into the source code:

On line 187 and 188 of create_heatmaps.py:

`
blocky_wsi_kwargs = {'top_left': None, 'bot_right': None, 'patch_size': patch_size, 'step_size': patch_size, 
	'custom_downsample':patch_args.custom_downsample, 'level': patch_args.patch_level, 'use_center_shift': heatmap_args.use_center_shift}
`

Note that patch_size is currently being passed in to the kwargs for 'step_size', instead of step_size. The fix should just be:

`
blocky_wsi_kwargs = {'top_left': None, 'bot_right': None, 'patch_size': patch_size, 'step_size': step_size, 
	'custom_downsample':patch_args.custom_downsample, 'level': patch_args.patch_level, 'use_center_shift': heatmap_args.use_center_shift}
`

Thanks!
Karthik

**Comment by fedshyvana** [comment]
hi - the blocky wsi heatmap by definition is non-overlapping so the step-size argument does not matter (think of it as the most computationally cheap WSI heatmap you can compute). The step-size arg is only used when creating the fine-grained heatmap, which is when you set compute_heatmap = True in the .yaml.
