### ISSUE TITLE
Number of Patches per Slide for TCGA-LUSC and TCGA-LUAD

### ISSUE THREAD

**Issue by tanakagirl** [mahmoodlab/CLAM#114]
Thanks for sharing the code and pertained models for a great work! :)

I am trying to evaluate the performance on TCGA-LUSC and TCGA-LUAD. I am using the provide toga.csv as parameters for patching. However it seems like I am getting much more number of patches per slide as compared to the data reported in the supplementary table 8 (9958). It seems like I am getting 50k+ on average. Am I doing sth wrong?

Thank you!

**Comment by fedshyvana** [comment]
I would guess it is probably because you are patching with --level 0 (which for most tcga slides means 40x) whereas we ran experiments at 20x.

**Comment by tanakagirl** [comment]
Thank you!

**Comment by scjjb** [comment]
Hi I have a question about this - I am getting the same issue of 50k+ patches, but I am using 512x512 patches at --level 0 then downsizing during feature extraction using --custom_downsample 2. Shouldn't this give me the ~10k patches you report as this is equivalent to 256x256 patches at 20x?

**Comment by scjjb** [comment]
Just realised I forgot to change the step size, my mistake!
