### ISSUE TITLE
Interpretation of the AUC in a summary result (reproducing RCC)

### ISSUE THREAD

**Issue by omniaalwazzan** [mahmoodlab/CLAM#115]
Hi, 
 
Finally, I’ve reached the end of the CLAM pipeline, and I would like to tell you that I wouldn’t be able to get to this point without your continuous support.

I am confused about understanding the summary result even after looking at some resolved issues(#94 ) regarding this matter.

Let me first explain my dataset to make it clear for you:

I have followed the same dataset in the CLAM paper, which is the RCC subtyping 

I have 284 slides PRCC TCGA-KIRP, 121 slides CRCC TCGA-KICH, and 519 slides CCRCC -KIRC.

The total number of diagnostic slides is 937.

I assumed the label for each type is like this:
Subtype_1= PRCC
Subtype_2=CRCC
Subtype_3=CRCC

I’ve used create_split_seq.py to split the dataset, and this is one example of a 50% training split. 

label column: label
label dictionary: {'subtype_1': 0, 'subtype_2': 1, 'subtype_3': 2}
number of classes: 3
slide-level counts:  
 0    297
2    519
1    121
Name: label, dtype: int64
Patient-LVL; Number of samples registered in class 0: 273
Slide-LVL; Number of samples registered in class 0: 297
Patient-LVL; Number of samples registered in class 1: 109
Slide-LVL; Number of samples registered in class 1: 121
Patient-LVL; Number of samples registered in class 2: 513
Slide-LVL; Number of samples registered in class 2: 519

number of training samples: 364
number of samples in cls 0: 112
number of samples in cls 1: 44
number of samples in cls 2: 208

number of val samples: 93
number of samples in cls 0: 29
number of samples in cls 1: 13
number of samples in cls 2: 51

number of test samples: 92
number of samples in cls 0: 30
number of samples in cls 1: 11
number of samples in cls 2: 51

First concern: What is the difference between the slide LVL and patient LVL? 

Second concern: After I trained the model on 50% of the training dataset, I evaluated and got this summary table

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/omnia/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/omnia/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/omnia/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

  | folds | test_auc | test_acc
-- | -- | -- | --
0 | 0 | 0.931110219 | 0.836957
1 | 1 | 0.936167727 | 0.836957
2 | 2 | 0.948137621 | 0.817204
3 | 3 | 0.954437176 | 0.824176
4 | 4 | 0.936995394 | 0.784946
5 | 5 | 0.949174054 | 0.866667
6 | 6 | 0.944884342 | 0.85
7 | 7 | 0.962047143 | 0.919192
8 | 8 | 0.906294443 | 0.758242
9 | 9 | 0.941699149 | 0.793478

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>

In Clam’s paper, you claimed that you took the average of AUC and have achieved (AUC= 0.9705 ± 0.0163) in supplementary table 1 page 11 in the supplemental material for the 50%. However, in my experiment, from the above table, the avg AUC is 94%, which is relatively low compared to yours. What are your kind thoughts regarding this? I used the clam_mb model.

Note: I have noticed that in the above table, fold#7 achieved the best test_auc. And I guess that’s because the split of this fold was a 100 in the testing, am I right?
Split for fold 7:
number of training samples: 365
number of samples in cls 0: 113
number of samples in cls 1: 44
number of samples in cls 2: 208

number of val samples: 93
number of samples in cls 0: 28
number of samples in cls 1: 13
number of samples in cls 2: 52

number of test samples: 100
number of samples in cls 0: 37
number of samples in cls 1: 12
number of samples in cls 2: 51

 
Sorry for the long post, and thanks in advance.
Omnia

**Comment by fedshyvana** [comment]
Hey Ominia.
Regarding your Q1: some patients have multiple slides, so when we're splitting train/val/test we make sure all slides from the same patient end up in the same split. So patient lvl is number of patients, slide lvl is number of slides. That's all that is, we still do training/evaluation on a per slide basis. 

Regarding your Q2, 94 does seem kind of low. Did you process the data at 20x or 40x? and what's the exact model configuration (i.e. the command) you used to run training?

**Comment by omniaalwazzan** [comment]
Thanks for the quick response. 

I see, now I got it for Q1.

For Q2, how do I know the magnification of the slide 20x or 40x? sorry to ask this type of question but I am very new to the field, have started 2 months ago :) 
 
the model configuration I used for the mentioned summary table is as the following:
python main.py --drop_out --early_stopping --lr 2e-4 --k 10 --label_frac 0.5 --exp_code task_2_tumor_subtyping_CLAM_50 --weighted_sample --bag_loss ce --inst_loss svm --task task_2_tumor_subtyping --model_type clam_mb --log_data --subtyping --data_root_dir DATA_ROOT_DIR

**Comment by fedshyvana** [comment]
the model training command looks reasonable. So TCGA slides are typically 40X at --level 0. If you want 20x for 256 x 256 patches, you should patch at --level 0, --patch_size 512, --step_size 512, and then when extracting features run --custom_downsample 2, which will downsize the patches by a factor of 2.  If you didn't do this then you're most likely training at 40x. The fact that you seem to be getting somewhat worse performance might suggest for this task, 20x should work better.

**Comment by tanakagirl** [comment]
> the model training command looks reasonable. So TCGA slides are typically 40X at --level 0. If you want 20x for 256 x 256 patches, you should patch at --level 0, --patch_size 512, --step_size 512, and then when extracting features run --custom_downsample 2, which will downsize the patches by a factor of 2. If you didn't do this then you're most likely training at 40x. The fact that you seem to be getting somewhat worse performance might suggest for this task, 20x should work better.

Thank you for explaining. Are these configurations used in the original experiments for RCC subtyping and LUAD/LUSC subtyping? If I want to evaluate the performance of the pertained model provided on TCGA dataset, these are the configuration I should use for patching/feature extraction, correct?

Thanks

**Comment by fedshyvana** [comment]
yeah the general configuration is the same (although when the study was performed we used an older version of "CLAM" processing workflow before the code was cleaned up/refactored for public release so there might be minor differences here and there).

**Comment by omniaalwazzan** [comment]
> the model training command looks reasonable. So TCGA slides are typically 40X at --level 0. If you want 20x for 256 x 256 patches, you should patch at --level 0, --patch_size 512, --step_size 512, and then when extracting features run --custom_downsample 2, which will downsize the patches by a factor of 2. If you didn't do this then you're most likely training at 40x. The fact that you seem to be getting somewhat worse performance might suggest for this task, 20x should work better.

Thanks for clarifying this. 

I did patch at level 0 but the patch size was 265 as well as the step size. 

So your suggestion is : 

- repeat the experiment using 512 patch & step-size. 

- repeat the feature extraction using a custom_downsample=2 

I want to mention that I have 97% AUC on the 75% of the training, still not like the one in the CLAM paper(98) given that my dataset is bigger. I assume that I should get closer to CLAM AUC or better! 

 
Again many thanks for the explanation. 
Omnia

**Comment by micdic** [comment]
In order to work on 20x magnification, if I patch using --level 1, do i still need to use custom_downsample=2 in the feature extraction?.
I guess no, i.e. to patch at 20x i can simply use patch with --level 1 and on feature extraction leave default custo m_downsample = 1, ...correct?
Thanks.

**Comment by fedshyvana** [comment]
for Aperio Scanners, to the best of my knowledge, level 1 is 4x downsample relative to level 0. So if level 0 is 40x, level 1 will be 10x, which is why I patch at level 0 at 512 x 512, and then scale them to 256 x 256 before feature extraction to get 20x.

**Comment by micdic** [comment]
Ok, (my 2 cents) It's worth to check each WSI (.svs) in the dataset, because not always the available zoom level is 40x at level 0. It happens also to have 20x at level 0, so the risk is to have a dataset with different level of magnification for patches. It's possible to check the zoom available in the WSI with (from openslide):
objective_power = int(slide.properties[openslide.PROPERTY_NAME_OBJECTIVE_POWER])

Thanks for the answer.

**Comment by fedshyvana** [comment]
@micdic yes - you're correct. you should also check the mpp in addition to the objective power. we found sometimes the magnification specified in the metadata to be inconsistent with the mpp.

**Comment by Legendddd** [comment]
I am also trying to work on different magnifications, such as 5x,10x,20x.

Just to confirm for 40x WSI file:

- patch at --level 0, --patch_size 512, --step_size 512 extracting features run --custom_downsample 2 to work on 20x
- patch at --level 1, --patch_size 256, --step_size 256 extracting features run --custom_downsample 1 to work on 10x
- patch at --level 1, --patch_size 512, --step_size 512 extracting features run --custom_downsample 2 to work on 5x

Thanks

> > the model training command looks reasonable. So TCGA slides are typically 40X at --level 0. If you want 20x for 256 x 256 patches, you should patch at --level 0, --patch_size 512, --step_size 512, and then when extracting features run --custom_downsample 2, which will downsize the patches by a factor of 2. If you didn't do this then you're most likely training at 40x. The fact that you seem to be getting somewhat worse performance might suggest for this task, 20x should work better.
> 
> Thanks for clarifying this.
> 
> I did patch at level 0 but the patch size was 265 as well as the step size.
> 
> So your suggestion is :
> 
> * repeat the experiment using 512 patch & step-size.
> * repeat the feature extraction using a custom_downsample=2
> 
> I want to mention that I have 97% AUC on the 75% of the training, still not like the one in the CLAM paper(98) given that my dataset is bigger. I assume that I should get closer to CLAM AUC or better!
> 
> Again many thanks for the explanation. Omnia

**Comment by gexinh** [comment]
> @micdic yes - you're correct. you should also check the mpp in addition to the objective power. we found sometimes the magnification specified in the metadata to be inconsistent with the mpp.

Sorry for continuing this thread. 

I am very new to this field :) I was wondering if TCGA and CPTAC would exist various magnifications in the raw data, or even the inconsistent problem related to mmp? If so, how should I check the mmp for each slide? Thanks for your time in advance!

**Comment by ljhOfGithub** [comment]
How could I get the 512x512 patches at 20x instead of 256x256 patches?

**Comment by jchirkes** [comment]
Hello, I have images with a magnification of 40x at level 0. Since level 1 is 10x and I need 20x, I am patching at: 
--level 0, --patch_size 512, --step_size 512 extracting features run --custom_downsample 2 to work on 20x

I am still not getting great results, so I tried looking at the h5 files from the patches at result_directory. When I look at the patch sizes, the dimensions are 512x512 pixels. Is the downsample working correctly? Shouldn't the patch size now be 256x256?

To try and see what is going on, I did this again but to get a 10x magnification, so patch_size 1024, step_size 1024 and custom_downsample 4 (named results_10). Then, I ran everything for level 1 with patch_size 256 and no downsample (named results_10_new). If I am understanding things correctly, results_10 and results_10_new should be exactly the same. 
Even though the size of patches and dimension of features are the same, the features are different. I am not sure about what is going on. Could you tell me if I am doing things correctly?

**Comment by syy-create** [comment]
> Hello, I have images with a magnification of 40x at level 0. Since level 1 is 10x and I need 20x, I am patching at: --level 0, --patch_size 512, --step_size 512 extracting features run --custom_downsample 2 to work on 20x
> 
> I am still not getting great results, so I tried looking at the h5 files from the patches at result_directory. When I look at the patch sizes, the dimensions are 512x512 pixels. Is the downsample working correctly? Shouldn't the patch size now be 256x256?
> 
> To try and see what is going on, I did this again but to get a 10x magnification, so patch_size 1024, step_size 1024 and custom_downsample 4 (named results_10). Then, I ran everything for level 1 with patch_size 256 and no downsample (named results_10_new). If I am understanding things correctly, results_10 and results_10_new should be exactly the same. Even though the size of patches and dimension of features are the same, the features are different. I am not sure about what is going on. Could you tell me if I am doing things correctly?

Hello, do you understand what caused this? I have read your question and believe that your thoughts are the same as mine, but I don't know where I went wrong. Thanks for your time in advance!

**Comment by Studing-Forever** [comment]
> > Hello, I have images with a magnification of 40x at level 0. Since level 1 is 10x and I need 20x, I am patching at: --level 0, --patch_size 512, --step_size 512 extracting features run --custom_downsample 2 to work on 20x
> > I am still not getting great results, so I tried looking at the h5 files from the patches at result_directory. When I look at the patch sizes, the dimensions are 512x512 pixels. Is the downsample working correctly? Shouldn't the patch size now be 256x256?
> > To try and see what is going on, I did this again but to get a 10x magnification, so patch_size 1024, step_size 1024 and custom_downsample 4 (named results_10). Then, I ran everything for level 1 with patch_size 256 and no downsample (named results_10_new). If I am understanding things correctly, results_10 and results_10_new should be exactly the same. Even though the size of patches and dimension of features are the same, the features are different. I am not sure about what is going on. Could you tell me if I am doing things correctly?
> 
> Hello, do you understand what caused this? I have read your question and believe that your thoughts are the same as mine, but I don't know where I went wrong. Thanks for your time in advance!

Hello, have you solved this problem? I also have the same problem. Logically, the two should be equal.
