### ISSUE TITLE
Why give positive labels to the top_k patches with highest attention score directly.

### ISSUE THREAD

**Issue by WxpHB** [mahmoodlab/CLAM#120]
Hi, thanks for your excellent work, and there are someting confused me .In your paper the Section “Interpretability and Whole Slide Attention Visualization.”  you emphasized that “....However, caution should be taken not to overly rely on the attention heatmaps with the expectation that they can serve as pixel-perfect segmentation masks...” .  But the  function "inst_eval" in model_clam.py gives positive labels to the top_p patches with highest attention score directly，and the facts is that patches with hightest attention score don't must mean to be cancerous region.
Looking forward to your clearing up of my confusion.
Best regard

**Comment by WxpHB** [comment]
Can anybody give a hint to my question? And i sent emails to the authour of 《Data Efficient and Weakly Supervised Computational Pathology on Whole Slide Images》through different email address，but there's no reply . And i opened this issue here 8 days ago,no reply too.

**Comment by fedshyvana** [comment]
Hey, sorry for the slow turnaround - i'm completely swamped by coursework these days as it is near the end of the semester (and sorry if I missed it but i did not receive any emails). 

To clarify, inst_eval is only used during training to help the model learn a more discriminative feature space at the patch-level - it is just a trick we employed to try to improve the data-efficiency of the learning algorithm during training time. It is not used at test time to make predictions about the slide. The intuition is that patches that receive high attention should be characteristic of the class label while those that receive low attention should not - therefore we train a linear classifier to separate them in the feature space (think of it as putting the high-attention patches and low attention patches into different clusters). The two "clusters" don't necessarily need to be thought of as tumor vs. normal. For example, in cancer subtyping, we ask the model to put the high attention patches from slides with one subtype into a different cluster as high attention patches from slides with a different subtype.

**Comment by WxpHB** [comment]
Thanks for your good hints. I'll dive into the paper and code. I'll disturb you when doubt arise,forgive my troubling you.
