### ISSUE TITLE
Normal Lung Tissue

### ISSUE THREAD

**Issue by GeorgeBatch** [mahmoodlab/CLAM#123]
Dear authors,

Thank you for releasing your code!

I have downloaded the Lung Adenocarcinoma (LUAD) and Lung Squamous Cell Carcinoma (LUSC) TCGA slides. I was not able to find the normal-tissue slides there. Can you please share a link/instructions for downloading those if you still have them?

Many thanks,
George Batchkala

**Comment by fedshyvana** [comment]
We did not use normal lung slides for this project. I know there's some normal lung slides from CPTAC cohort though, but we did not use them in the study.

**Comment by GeorgeBatch** [comment]
Thank you very much! I checked the paper and indeed it says that you excluded normal lung tissue. Sorry for the confusion.

**Comment by bryanwong17** [comment]
Hi @GeorgeBatch , could you please share how to download LUAD and LUSC TCGA slides? Additionally, could you provide guidance on preprocessing them into patches to achieve the same results as those used in CLAM's experiment?

**Comment by GeorgeBatch** [comment]
@bryanwong17, I wrote these instructions for myself in case I need to do it agian: https://github.com/GeorgeBatch/TCGA_lung

**Comment by bryanwong17** [comment]
@GeorgeBatch Thank you for sharing!
