### ISSUE TITLE
Questions about CAMELYON16

### ISSUE THREAD

**Issue by pzSuen** [mahmoodlab/CLAM#126]
Hello,
I have a question about the way you extract patches at CAMELYON16.
You said in the paper, "We combined CAMELYON16 and CAMELYON17 into a single dataset with a total of 899 slides (591 negative and 308 positive) from 499 cases. The mean number of patches extracted per slide at ×40 magnification is 41,802."

But when I check the paper of CAMELYON16, I found part of its data with a 20x objective lens(as seen in the picture capture from 10.1001/jama.2017.14585 ). So my question is how do you extract patches at 40x for them?

![image](https://user-images.githubusercontent.com/43957007/170231570-9bf370e2-745b-4e50-b3a3-229926a63468.png)

**Comment by fedshyvana** [comment]
not super familiar with scanners - but if you look at the description, the 20x objective lens produces mpp (micron per pixel) of 0.243 um which basically identical to the 40x objective with mpp of 0.226, which I believe is ultimately is what we want (i.e. the same object with the same physical dimension should occupy comparable number of pixels when digitized by the two different scanners). So effectively both scanners create 40x images (if you look at a 20x image from either TCGA/CPTAC, the mpp will be around 0.5um).
