### ISSUE TITLE
Loss of information in the resultant stitches

### ISSUE THREAD

**Issue by mlandcv** [mahmoodlab/CLAM#127]
After running create_patches_fp.py on my .svs wsi, I end up with the following file in the stitches folder.
![LeicaAT2_1](https://user-images.githubusercontent.com/28726924/170464323-7d441e12-0361-46c5-93a3-e7638727de51.png)
 
Is there a way we can prevent the loss of information in these stitches. Can we derive zoomed in patches and stitch them up for high quality stitched outputs using create_patches_fp.py script? I am fairly new to WSI and any comment will help.

**Comment by fedshyvana** [comment]
the stiching is just for you to visualize that the patching has captured the tissue regions/filtered out the background. It's not meant for doing actual analysis.
