### ISSUE TITLE
.pt is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by cpoptic** [mahmoodlab/CLAM#128]
PyTorch 1.3 is having trouble loading a `.pt` file, which it thinks is a zip archive.

>   File "/my_conda_env/lib/python3.7/site-packages/torch/serialization.py", line 599, in _load
>     raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
> RuntimeError: /my_data_directory/features/ResNet50_ImageNet/pt_files/GO30140_07290266C0001S_HE_mrxs.pt is a zip archive (did you mean to use torch.jit.load()?)
>

**Comment by fedshyvana** [comment]
so upon some investigation, apparently pytorch 1.6+ saves .pt as zip files. Did you process/obtain the .pt files on a different machine using pytorch 1.6+, and try to load them on a machine with pytorch 1.3? If you use the same version across the two machines there shouldn't be an issue is my understanding.
