### ISSUE TITLE
Excluding tissue patch covered in pen marker?

### ISSUE THREAD

**Issue by rushin682** [mahmoodlab/CLAM#130]
Hello,

I was just wondering if there is a functionality and/or argument that I could use in the feature extraction phase to ignore patching of regions with pen marking on them? If so, can you please help with a description on how to use it?

Thank you!

**Comment by rushin682** [comment]
Found similar resolved issue

**Comment by claudiofernandez** [comment]
Which was the similar resolved issue? I am facing the same problem, in TCGA-BRCA there are some slides with pen marker covering the tissue.

**Comment by rushin682** [comment]
#104  The author ended up implementing his own solution. I checked his GitHub repo. Maybe [this implementation](https://github.com/KarthikNair1/CLAM) helps

**Comment by claudiofernandez** [comment]
Thank you very much for your quick reply @rushin682 . However this involves patching the whole dataset, and extracting and saving masks (from HISTOQC) which is quite inefficient. I will try to find a solution to check the patches "on the fly" in CLAM.
