### ISSUE TITLE
Finetuning before Extracting Features

### ISSUE THREAD

**Issue by Tejussurendran** [mahmoodlab/CLAM#133]
Hello!

FIrst off thank you for making this tool available!

I would like to preface this by saying that I am relatively new to machine learning and pytorch, so what I am saying may not even be possible, however I thought I would ask anyways. 

I was wondering whether or not it would be possible to finetune/updating weights before feature extracting. From what I understood it would involve some kind of "for param in model.parameters(): param.requires_grad = True", however I am not able to find the appropriate location to make that change, as wherever I have tried it, the feature values that are being outputted to the .h5 files remains the same. And based on the print_network(model) it appears that the model is not being finetuned as the the total number of trainable parameters is 0.

Any suggestions would be greatly appreciated. 

Thank you!

**Comment by fedshyvana** [comment]
you can train your own encoder using either ROI-level annotation, or self-supervised learning (e.g. MAE, SimCLR, DINO, MoCo) but they require their own implementation separate from what this codebase provide. If you do end-up going that route, to use those encoders for feature extraction, you just have to modify the encoder definition/construction to use your own custom encoder here: https://github.com/mahmoodlab/CLAM/blob/1a92ef234411b44ec9ba27551307aea1143b5b4e/extract_features_fp.py#L88
