### ISSUE TITLE
ModuleNotFoundError: No module named 'topk'

### ISSUE THREAD

**Issue by ASKanse** [mahmoodlab/CLAM#14]
So i followed all the steps starting with initializing the environment with the provided "clam.yaml" file but when running the training part i am facing this error. I searched in the dependencies of the yaml file but couldn't find any for the "topk" 

error:
"""
Init Model... Traceback (most recent call last):
  File "main.py", line 218, in <module>
    results = main(args)
  File "main.py", line 49, in main
    results, test_auc, val_auc, test_acc, val_acc  = train(datasets, i, args)
  File "/home/abhiraj/DDP/CLAM/CLAM/utils/core_utils.py", line 140, in train
    from topk import SmoothTop1SVM
ModuleNotFoundError: No module named 'topk'
"""

please let me know how to resolve this

(also in create_splits_seq.py there seems to be a syntax error in line 
if (args.task == tcga_kidney)
it should have been 
if (args.task == tcga_kidney_cv)
according to me)

**Comment by ASKanse** [comment]
ok i found this help full : https://github.com/oval-group/smooth-topk
but still i get this error:
Init Model... Traceback (most recent call last):
  File "main.py", line 218, in <module>
    results = main(args)
  File "main.py", line 49, in main
    results, test_auc, val_auc, test_acc, val_acc  = train(datasets, i, args)
  File "/home/abhiraj/DDP/CLAM/CLAM/utils/core_utils.py", line 140, in train
    from topk import SmoothTop1SVM
ImportError: cannot import name 'SmoothTop1SVM' from 'topk' (unknown location)

**Comment by fedshyvana** [comment]
Hi, this was mentioned in our installation guide, but to install topk, you should:
```
git clone https://github.com/oval-group/smooth-topk.git
cd smooth-topk
python setup.py install
```

**Comment by ASKanse** [comment]
Thanks a lot!
Sorry i missed it in the guide.

**Comment by ASKanse** [comment]
Hey @fedshyvana ! I was training the model and about 5 folds down the line the connection to my the remote system was lost due to a system reboot. Is there a way to restart training from the last saved model?
Thanks!

**Comment by fedshyvana** [comment]
> Hey @fedshyvana ! I was training the model and about 5 folds down the line the connection to my the remote system was lost due to a system reboot. Is there a way to restart training from the last saved model?
> Thanks!

You can restart training from the latest fold using the --k_start argument. so if your training got interrupted on the 4th fold (k=0,1,2,3), you can rerun the command with --k_start 3 to restart from the 4th fold.
