### ISSUE TITLE
Ome.tiff file reading issues

### ISSUE THREAD

**Issue by Tejussurendran** [mahmoodlab/CLAM#140]
Hello,

I was trying to read in some .ome.tiff files and it says that "level_dim 67727 x 45960 is likely too large for successful segmentation, aborting". I tried changing the seg_level, however it threw an error saying the value was outside the tuple for dimensions.

Is there any way to resolve this issue?

The reason I have these .ome.tiff files, is due to some image registration I have performed on the images before trying to break them into patches.

Thank you for your help!

**Comment by fedshyvana** [comment]
you can maybe try commenting out the if block to see if you can proceed without issue: https://github.com/mahmoodlab/CLAM/blob/1a92ef234411b44ec9ba27551307aea1143b5b4e/create_patches_fp.py#L174
