### ISSUE TITLE
Error for the heatmap creation

### ISSUE THREAD

**Issue by archanabhardwaj** [mahmoodlab/CLAM#141]
Hi there

I am planning to use "CLAM" for my WSI datasets. First, I tried to run this tool on test data, everything works fine until evaluation step. But I am facing issue for the heatmap visualization. I made changes in config_template.yaml as per the requirement but it gives an error :

  **File "create_heatmaps.py", line 280
    mask = wsi_object.visWSI(**vis_params, number_contours=True)
                                         ^
SyntaxError: invalid syntax**

For another cross check, I tried to run the actual config_template.yaml with the data already available on the website. But running sample data with "create_heatmaps.py" and "config_template.yaml" still shows me same error . 

I would be grateful if you can help me to fix this issue. 

Thanks in advance

**Comment by rohitkukq** [comment]
Did you change anything in the create_heatmaps.py file ?

**Comment by fedshyvana** [comment]
i have not had any one report there is a bug in the heatmap generation code - if you still encounter issue I will look into it if you can provide me instructions on reproducing the error.
