### ISSUE TITLE
Non-unique folds from create_splits_seq.py

### ISSUE THREAD

**Issue by scjjb** [mahmoodlab/CLAM#142]
I have realised that the create_splits_seq.py is not creating independent test sets. For example, when I run:

python create_splits_seq.py --task custom_1vsall --seed 1 --label_frac 1 --val_frac 0.2 --test_frac 0.1 --k 10

My intention is to get 10 independent test sets, each containing 10% of the total available data. However, what I'm actually getting is 10 overlapping test sets that add up to the wrong number of WSIs. Is there any way to fix this?

**Comment by fedshyvana** [comment]
It is by design since we use monte carlo cross-validation instead of k-fold cross-validation. see here: https://stats.stackexchange.com/questions/51416/k-fold-vs-monte-carlo-cross-validation
