### ISSUE TITLE
Memory Error While Creating heatpmaps for Camelyon Data

### ISSUE THREAD

**Issue by rohitkukq** [mahmoodlab/CLAM#143]
When I am trying to create heatmaps for Camelyon dataset on a single file I get this error. 

Unable to allocate 40.3 GiB for an array with shape (110592, 48896) and data type int64

**Comment by fedshyvana** [comment]
it just means you don't have enough RAM on your system - you can try to create the heatmap at a lower downsample or move to a system with more RAM.
