### ISSUE TITLE
Training 20x and 40x together ?

### ISSUE THREAD

**Issue by shubhaminnani** [mahmoodlab/CLAM#147]
Hi @fedshyvana ,

Just a question regarding the code, can we train 20x and 40x magnification WSIs in single training?
If so, what would be patch level, patch size or step size. 

Thanks, 
Shubham

**Comment by fedshyvana** [comment]
Hi, you can if you process them to be the same magnification. i.e. if you have both 20x and 40x WSIs, then you should probably extract features from all slides at 20x. This means you should use different patch-levels for processing 20x and 40x WSIs such that it corresponds to the same magnification.

**Comment by shubhaminnani** [comment]
Thanks!

**Comment by maduc7** [comment]
Hi, 
How to proceed if for the 40x slides, the level 1 is 4 and not 2? 
This would lead to 10x instead of 20x. I did not found any more a way to downsample to 2 is there a new way to do it?
Thanks
