### ISSUE TITLE
patching slides with ndpi extension

### ISSUE THREAD

**Issue by fnurkinali** [mahmoodlab/CLAM#148]
Hello,

I need to patch slides with ndpi extension. create_patches_fp.py is not able to segment tissue with default parameters. There is a --slide_ext parser for feature extraction, but I can't find it for patching.

Can you help me how to patch ndpi slides?

Thank you!

**Comment by ptomaszewska** [comment]
Hello,
@fnurkinali I encountered the same problem. The images with ndpi extension were not properly segmented using `create_patches_fp.py`. I can see that you closed an issue. Could you share what you changed in the default settings to make it work better?

**Comment by Legendddd** [comment]
Use different preset will fix this.
bwh_biopsy.csv should work pretty well (basically you need to increase the threshold, e.g. increase sthresh)
this is what they reposed to me before. #95

**Comment by ptomaszewska** [comment]
@Legendddd - Thank you for the valuable hint! It worked :)
