### ISSUE TITLE
Improving GPU Utilization

### ISSUE THREAD

**Issue by Tejussurendran** [mahmoodlab/CLAM#149]
Hello,

I was wondering if there were any recommendations for improving the code's GPU utilization while doing feature extraction as I noticed when using nvidia-smi that it says the GPU utilization is 0%. 

Thank you!

**Comment by fedshyvana** [comment]
Are you certain you're actually using the GPUs (i.e. torch.cuda_is_available()) ? The feature extraction uses dp instead of ddp so its not as efficient - but GPU utilization of 0% seems unexpected...

**Comment by Tejussurendran** [comment]
Hello, So I tried the command you suggested and it is returning TRUE. Do you suggest any other methods, as I currently am trying to do feature extraction on 1600 images, and the estimated time to finish is around 4-5 days. 

Thank you!

**Comment by fedshyvana** [comment]
can you let know me exactly what command you ran?

**Comment by Tejussurendran** [comment]
So the command I ran was ' CUDA_VISIBLE_DEVICES=0,1 python extract_features_fp.py --data_h5_dir /SeaExpCIFS/Restricted/ADC_CASES_HE_AT8_Patches/ --data_slide_dir /SeaExpCIFS/Restricted/ADC_CASES_HE_AT8/ --csv_path /home/tsurendr/ADC_Spreadsheet/ADC_CASES_HE_AT8.txt --feat_dir /SeaExpCIFS/Restricted/ADC_CASES_HE_AT8_TESTING --batch_size 512 --slide_ext .svs'

Also, the image sizes are between 40000 -60000 pixels per dimension. And at 256x256 per patch I would imagine there are probably 10000+ patches.

**Comment by Tejussurendran** [comment]
I am also using 2 RTX 3090s, and I was thinking about increasing the batch size as well as number of workers

**Comment by fedshyvana** [comment]
I see - i think unfortunately i've found increasing the number of works/using larger batch sizes might not give you any performance increase if you're bottlenecked by how fast you can read those patches from disk. So I would maybe try using faster storage if possible - you might see a bigger improvement there.
