### ISSUE TITLE
How to disable mutual exclusivity?

### ISSUE THREAD

**Issue by qinghezeng** [mahmoodlab/CLAM#15]
Hi, I am trying to apply CLAM to a multi-class problem. For my data, the label classes are more like predicting cancer grades. Is it possible to remove the mutual exclusivity? Thank you!

**Comment by fedshyvana** [comment]
Hi, yes, it's would not be enabled as long as you don't use --subtyping.

**Comment by qinghezeng** [comment]
Thank you for your answer!
There is one more thing confusing me. For sub-typing problem, for example, in `main.py` line 174:
```
    if args.model_type == 'clam':
        assert args.subtyping
```
Does it mean the --subtyping flag must be used? However, in line 95:
```
parser.add_argument('--model_type', type=str, choices=['clam_sb', 'clam_mb', 'mil'], default='clam_sb', 
                    help='type of model (default: clam_sb, clam w/ single attention branch)')
```
We can see `'clam'` option is not accepted for `--model_type`. So why do we need this?

**Comment by fedshyvana** [comment]
Hi, sorry for the confusion, first of all: the assertion statement is just for my own book-keeping i.e. i wanted to use subtyping for that specific task I defined and wanted to make sure that when I was training with that task, i would not forget to enable it. So no, you do not have to use the subtyping flag for any specific task depending on your needs. second of all: 'clam' is just something i forgot to update in the code ('clam_sb' and 'clam_mb' used to be a single option called 'clam') - i will correct that shortly, thanks for pointing out.

**Comment by qinghezeng** [comment]
Thank you so much for your detailed explanation!!

**Comment by mayurmallya** [comment]
Hi,

I'm having a hard time understanding the difference between the two input arguments: subtyping and no_inst_cluster. 
I mean, isn't ```python main.py --subtyping --no_inst_cluster``` same as simply ```python main.py```?

Please let me know if I'm missing something here.

Thank you in advance!
