### ISSUE TITLE
"--patch" in create_patches.py and create_patch_fp.py

### ISSUE THREAD

**Issue by luojing1030** [mahmoodlab/CLAM#151]
Thank you for your great work.
when I use the parameters "--patch" in running create_patches.py or create_patches_fp.py, (i want to save the patches),there emerging the error:
the error is about the wholeSlideImage.py, for create_patch_fp.py, "line 374, n_contours = len(self.contours_tissue, TypeError:object of type "NoneType has no len()" ; for create_patch.py, "line 243,contour_holes = self.holes_tissue, AttributeError:'WholeSlideImage' object has no attribute 'holes_tissue', and another error, "line 248, for  idx. cont in enumerate(contours): TypeError:'NoneType' object is not iterable. could you tell me how to solve it.

**Comment by luojing1030** [comment]
> Thank you for your great work. when I use the parameters "--patch" in running create_patches.py or create_patches_fp.py, (i want to save the patches),there emerging the error: the error is about the wholeSlideImage.py, for create_patch_fp.py, "line 374, n_contours = len(self.contours_tissue, TypeError:object of type "NoneType has no len()" ; for create_patch.py, "line 243,contour_holes = self.holes_tissue, AttributeError:'WholeSlideImage' object has no attribute 'holes_tissue', and another error, "line 248, for idx. cont in enumerate(contours): TypeError:'NoneType' object is not iterable. could you tell me how to solve it.

**Comment by MohammedHAlali** [comment]
Maybe the path to the svs files contains no files. So the in `create_pathces_fp.py` is reading nothing, hence giving an error of: `NoneType`

**Comment by siemdejong** [comment]
Never mind. The preset used didn't work for me, resulting in no contours. I had to provide my own preset for patching.
