### ISSUE TITLE
Core dump while running create_heatmaps.py

### ISSUE THREAD

**Issue by yqlwqj** [mahmoodlab/CLAM#152]
Hi,  I have core dumped while running CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps.py --config config_template.yaml. All other steps are going well . Anyone can help on this ？

**Comment by fedshyvana** [comment]
probably because you ran out of system memory.... try generating the heatmap at a lower resolution if your system does not have a lot of RAM.

**Comment by yqlwqj** [comment]
My system memory is 64 G. May I know minimum configuration for this? thanks

**Comment by fedshyvana** [comment]
i would try the level corresponding to 10x in your WSIs
