### ISSUE TITLE
Pen Marking of Slides handled by CLAM

### ISSUE THREAD

**Issue by shubhaminnani** [mahmoodlab/CLAM#157]
Hi @fedshyvana 
Do CLAM handle the penn marked slides while segmenting ? Dont have any mask for tissue. So whatever CLAM is doing is their a way to tackle penn marking?

Thanks!

**Comment by fedshyvana** [comment]
Penmarks are not handled unfortunately - although for what it's worth if your goal is to simply train a classifier, we've found that the model is able to ignore the penmarkings and focus on tissue regions via attention. Although if your goal is perform other types of analysis then this could become an issue.

**Comment by shubhaminnani** [comment]
Thank you for your quick response. Attention is received by pen markings even though it is training a classifier. Will need to include a pre-processing seems to be.
