### ISSUE TITLE
How to maintain reference patch size of 256x256

### ISSUE THREAD

**Issue by Tejussurendran** [mahmoodlab/CLAM#159]
Hello,

I have an image that is too big to process without downsampling, however when I change the patch_level it appears that the reference patch size also changes, thus changing the coordinates of the segmentation. I was wondering if there was a way to downsample the image while maintaining the original patch size of 256x256 for the coordinate locations. 

Thank you

**Comment by Tejussurendran** [comment]
Or is there a way to downsample the entire image before segmenting it and trying to extract coordinates?

**Comment by fedshyvana** [comment]
hey sorry i missed this, but the coordinates are always with respect to the original magnification no matter which level you use for segmenting or patching.

**Comment by lsnls** [comment]
Hello, @fedshyvana , 

If I run the command `python create_patches_fp.py --patch_size 256 --patch_level 1 --seg --patch --stitch `, which level is the patch size 256 based on?

Looking forward to your reply. Thank you so much!
