### ISSUE TITLE
Custom Downsample in create_patches_fp

### ISSUE THREAD

**Issue by shubhaminnani** [mahmoodlab/CLAM#162]
Hi,
Is there a reason custom down sample is removed from fast pipeline, create_patches_fp.py?

Thanks!

**Comment by shubhaminnani** [comment]
Its converted in features. Thanks!

**Comment by maduc7** [comment]
Hi @shubhaminnani What do you mean by its converted in features?
I actually would need to downsample by 2 and I am not sure how to do that.
Thanks
