### ISSUE TITLE
Patch magnification

### ISSUE THREAD

**Issue by bryanwong17** [mahmoodlab/CLAM#165]
May I know to patch at 20x instead of 40x? Is there a value I should change in patch_level?

**Comment by fedshyvana** [comment]
sorry for the late reply! but you should set the patch-level according to the WSI dataset you're using e.g. in my house, the hospital's scanner produces WSIs for which the level 0 is 40x, level 1 is 20x etc., but you can verify this by opening the slide using viewers such as QuPath or using openslide to read the metadata of the slide.
