### ISSUE TITLE
Unable to install on my windows using anaconda 3

### ISSUE THREAD

**Issue by Arita16** [mahmoodlab/CLAM#167]
the error that I am getting is :

ResolvePackageNotFound:
  - xorg-libxext==1.3.4=h516909a_0
  - xorg-xextproto==7.3.0=h14c3975_1002
  - matplotlib==3.1.1=py37h5429711_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - ninja==1.9.0=py37hfd86e86_0
  - h5py==2.10.0=nompi_py37h513d04c_102
  - sip==4.19.8=py37hf484d3e_0
  - ncurses==6.2=he6710b0_0
  - xorg-renderproto==0.11.1=h14c3975_1002
  - cython==0.29.15=py37he6710b0_0
  - numpy==1.18.1=py37h4f9e942_0
  - pango==1.42.4=h7062337_3
  - grpcio==1.27.2=py37hf8bcb03_0
  - cudatoolkit==10.1.243=h6bb024c_0
  - librsvg==2.46.2=h33a7fed_1
  - readline==8.0=h7b6447c_0
  - libgcc==7.2.0=h69d50b8_2
  - glib==2.63.1=h5a9c865_0
  - libxml2==2.9.9=hea5a465_1
  - libedit==3.1.20181209=hc058e9b_0
  - python==3.7.7=hcf32534_0_cpython
  - libpng==1.6.37=hbc83047_0
  - mkl_random==1.1.0=py37hd6b4f25_0
  - tensorboard==1.14.0=py37hf484d3e_0
  - markupsafe==1.1.1=py37h7b6447c_0
  - freetype==2.9.1=h8a8886c_1
  - libxcb==1.13=h1bed415_1
  - xorg-libx11==1.6.9=h516909a_0
  - libuuid==2.32.1=h14c3975_1000
  - tk==8.6.8=hbc83047_0
  - mkl_fft==1.0.15=py37ha843d7b_0
  - pixman==0.38.0=h7b6447c_0
  - xz==5.2.4=h14c3975_4
  - cairo==1.16.0=h18b612c_1001
  - libtiff==4.1.0=h2733197_0
  - jpeg==9b=h024ee3a_2
  - ptyprocess==0.6.0=py37_0
  - gobject-introspection==1.56.1=py37hbc4ca2d_2
  - harfbuzz==2.4.0=h37c48d4_1
  - pyrsistent==0.15.7=py37h7b6447c_0
  - hdf5==1.10.5=nompi_h3c11f04_1104
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - fribidi==1.0.9=h516909a_0
  - pyzmq==18.1.1=py37he6710b0_0
  - python-spams==2.6.1=py37h55324e4_1204
  - pcre==8.43=he6710b0_0
  - xorg-libxrender==0.9.10=h516909a_1002
  - libffi==3.2.1=hd88cf55_4
  - graphite2==1.3.13=h23475e2_0
  - gdk-pixbuf==2.36.9=1
  - dbus==1.13.12=h746ee38_0
  - pyqt==5.9.2=py37h05f1152_2
  - pytorch==1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - tensorflow-base==1.14.0=mkl_py37h7ce6ba3_0
  - tensorflow==1.14.0=mkl_py37h45c423b_0
  - openssl==1.1.1e=h7b6447c_0
  - tornado==6.0.4=py37h7b6447c_1
  - zlib==1.2.11=h7b6447c_3
  - c-ares==1.15.0=h7b6447c_1001
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - pillow==7.0.0=py37hb39fc2d_0
  - xorg-xproto==7.0.31=h14c3975_1007
  - icu==58.2=h9c2bf20_1
  - zeromq==4.3.1=he6710b0_3
  - mistune==0.8.4=py37h7b6447c_0
  - gstreamer==1.14.0=hb453b48_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - libprotobuf==3.11.4=hd408876_0
  - gmp==6.1.2=h6c8ec71_1
  - sqlite==3.31.1=h7b6447c_0
  - wrapt==1.12.1=py37h7b6447c_1
  - kiwisolver==1.1.0=py37he6710b0_0
  - cffi==1.14.0=py37h2e261b9_0
  - xorg-libice==1.0.10=h516909a_0
  - qt==5.9.7=h5867ecd_1
  - fontconfig==2.13.1=he4413a7_1000
  - libgfortran-ng==7.3.0=hdf63c60_0
  - xorg-kbproto==1.0.7=h14c3975_1002
  - expat==2.2.6=he6710b0_0
  - mkl-service==2.3.0=py37he904b0f_0
  - scipy==1.4.1=py37h0b6359f_0
  - libcroco==0.6.13=h8d621e5_0
  - numpy-base==1.18.1=py37hde5b4d6_1
  - libiconv==1.15=h516909a_1006
  - zstd==1.3.7=h0b5b093_0
  - intel-openmp==2019.4=243
  - mkl==2019.4=243
  - xorg-libsm==1.2.3=h84519dc_1000
  - libsodium==1.0.16=h1bed415_0

**Comment by fedshyvana** [comment]
sorry for the late reply, I have never tried to use CLAM on windows - if the conda env file fails to install correctly I believe you can always try to install dependencies yourself directly using anaconda.
