### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by qshwan** [mahmoodlab/CLAM#168]
main.py
File "/data/qsh/CLAM-master/utils/utils.py", line 150, in make_weights_for_balanced_classes_split
    weight_per_class = [N/len(dataset.slide_cls_ids[c]) for c in range(len(dataset.slide_cls_ids))]
  File "/data/qsh/CLAM-master/utils/utils.py", line 150, in <listcomp>
    weight_per_class = [N/len(dataset.slide_cls_ids[c]) for c in range(len(dataset.slide_cls_ids))]
ZeroDivisionError: float division by zero

**Comment by MohammedHAlali** [comment]
Make sure that `len(dataset.slide_cls_ids)` is greater than 0, and also `len(dataset)` is greater than 0, from the beginning.
