### ISSUE TITLE
Coordinates mismatch

### ISSUE THREAD

**Issue by nam1410** [mahmoodlab/CLAM#172]
@fedshyvana 

When I try to print the shape of "data" from
https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/core_utils.py#L234
I get the size (M, 1024)

However, if I try to print the shape of "features" from
https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/create_heatmaps.py#L34
I get a different size (N, 1024) for the same slide_id.

Note: Magnification levels are the same for both images, and I have not considered any explicit ROIs.

Kindly look into this.

Thank you.

**Comment by fedshyvana** [comment]
I don't think create_heatmaps use the same set of features/coordinates as what you previously generate/store by default. But you can specify the same process list with same patching/segmentation parameters as what you used before if you want to reproduce the original setting.

**Comment by nam1410** [comment]
Thank you. I have figured out the mistake while passing the coordinates to the block map. (I was maintaining the same setting throughout the process)
