### ISSUE TITLE
Heatmaps reversed

### ISSUE THREAD

**Issue by nam1410** [mahmoodlab/CLAM#173]
@fedshyvana 

I have been generating some heatmaps, and I see that if I use 

cmap = cmap.reversed()

after the following line, I get heatmaps closer to the expectations of a clinical expert.

https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/wsi_core/WholeSlideImage.py#L624

I'm not sure why this happens. Can you please explain?

**Comment by nam1410** [comment]
@fedshyvana 

Can you please look into this?

**Comment by fedshyvana** [comment]
I don't think there's any issue with the heatmap code - this could be a unique phenomenon to the task/dataset you're using. Sorry I am unable to comment on it.
