### ISSUE TITLE
something unclear in stitches after using create_patches_fp.py

### ISSUE THREAD

**Issue by qidog** [mahmoodlab/CLAM#175]
I have update my pixman version to 0.40.0
![image](https://user-images.githubusercontent.com/61582559/218955811-67f7d674-f3b9-4445-9b36-346977e6d31a.png)
But I also have the same problem like problem2 in #98.
![image](https://user-images.githubusercontent.com/61582559/218956132-c732168f-02f2-42fa-8faa-2f5a62f45f53.png)

**Comment by fedshyvana** [comment]
not sure, how did you install pixman? could you try uninstall and conda install -c anaconda pixman instead?
