### ISSUE TITLE
Problems segmentiong Ventana bif WSI

### ISSUE THREAD

**Issue by Tato14** [mahmoodlab/CLAM#177]
Thanks for the great tools. I am trying to tile and segment some Ventana bif slides using your `create_patches_fp.py` script and I am getting a couple of problems:

1) The images can be segmented quite accurately but the thumbnails in the "masks" directory are somehow incorrectly shown. Here is an example:
![image](https://user-images.githubusercontent.com/33808607/220875453-e5e5136e-9e62-4998-8d0a-8a9b52f2033c.png)

Do you know why is this noise in the image? 

2) On some bif images (DP200 scanned) openslide throws an error `Bad direction attribute "LEFT"`

I found in the openslide repor than this problem is actually solved in [this PR](https://github.com/openslide/openslide/pull/395). Is this something you experienced before?

Thanks

**Comment by fedshyvana** [comment]
regarding:
 1. please verify that you're using pixman > 0.38 (e.g. 0.40). upgrading to pixman 0.40.0 should solve the issue - this can be done via conda. 
 2. I am not sure unfortunately - i have never worked with bif images.

**Comment by Tato14** [comment]
It seems that the pixman=0.40.0 is not compatible with the clam.yaml file for setting up the conda env
