### ISSUE TITLE
I wrote about the masking part before, but it's not solved.

### ISSUE THREAD

**Issue by JaeHyeok-2** [mahmoodlab/CLAM#178]
<img width="337" alt="image" src="https://user-images.githubusercontent.com/89520646/222957135-9ed1abf3-97e0-4820-acac-2770c84e138f.png">

![image](https://user-images.githubusercontent.com/89520646/222957206-3a044c8c-4c6f-479e-8640-6f464a162a1a.png)

As a solution, it is said that you can update the pixman version to 0.40.0 or higher, but it is not solved.

**Comment by Irina-Zhang** [comment]
Hi I followed [this answer](https://github.com/openslide/openslide/issues/291#issuecomment-722935212) and it worked for me with pixman 0.40 :)

**Comment by JaeHyeok-2** [comment]
> Hi I followed [this answer](https://github.com/openslide/openslide/issues/291#issuecomment-722935212) and it worked for me with pixman 0.40 :)

Thanks to you, it has been resolved.
