### ISSUE TITLE
Use feature extraction files to train a ML model

### ISSUE THREAD

**Issue by Tato14** [mahmoodlab/CLAM#179]
Hi,
First of all, thank you for the great tool!
I am looking for a way to use the features extracted with `extract_features_fp.py`. Ideally, I would like to use them together with some clinical data to train a mache learning classifier (random forest, xgboost or something like this).

However, since the number of features extracted is different between images, I am unsure how to reduce the number of features of the `h5` files into something with a common shape for all images used. I was thinking of using PCA for this but I would like to know if you have any previous experience on this or you have a better idea.

I am also aware that you developed [PORPOISE](https://github.com/mahmoodlab/PORPOISE) and I am planning to give it a try but the number of samples is rather small (~250) and maybe this method would need more samples to generalize.

**Comment by KKIverson** [comment]
> 

some question

**Comment by fedshyvana** [comment]
I think for your purposes you might want to look into methods that produce slide-level embeddings directly such as GigaSSL, HIPT, etc.
