### ISSUE TITLE
Image Augmentation

### ISSUE THREAD

**Issue by nabilapuspit** [mahmoodlab/CLAM#185]
Hi, thank you for making such a great framework!
however, I found that this framework not working so well on my project. I'm currently working on TCGA with very large data variations. I planned to apply image augmentation such as stain normalization towards this framework but unfortunately I'm having a hard time finding the right place. At first I planned to apply the stain norm in the `creating_patch_fp.py` , but as you said in the updates `README.md`, since 

> CLAM only requires image features for training, it is not necessary to save the actual image patches, the new pipeline rids of this overhead and instead only saves the coordinates of image patches during "patching" and loads these regions on the fly from WSIs during feature extraction.

I think it's not the right place. can you give me some advice about my problem? thank you!

**Comment by fedshyvana** [comment]
Hi, sorry for the super late reply, create_patch_fp doesn't actually handle the underlying image pixels of "patches", it just stores the coordinates. The actual images are streamed to the image encoder in extract_features_fp.py
You can see the images are read, and the transforms are applied here: https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/datasets/dataset_h5.py#L155 .
So you can consider modifying the dataset function by passing in a custom transform function that performs e.g. stainnorm or data augmentation.

**Comment by nabilapuspit** [comment]
I tried to apply [Torchstain](https://github.com/EIDOSLAB/torchstain.git) on the place you've recomend, but always got 

> IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.

as I discussed in this [issue](https://github.com/EIDOSLAB/torchstain/issues/1) but still haven't got the solution and don't know why. Can you help me to debug this issue?

**Comment by ShiCrazy** [comment]
> I tried to apply [Torchstain](https://github.com/EIDOSLAB/torchstain.git) on the place you've recomend, but always got
> 
> > IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.
> 
> as I discussed in this [issue](https://github.com/EIDOSLAB/torchstain/issues/1) but still haven't got the solution and don't know why. Can you help me to debug this issue?

Hello! I'd like to ask if you have already performed stain normalization using torchstain on CLAM? I saw your question in the torchstain's issue as well, and it seems quite difficult to perform such an operation in the create_patches_fp.py. Should it be done in create_patches.py instead？

**Comment by ericwang10** [comment]
Hi, I was wondering if you guys had any updates regarding applying stain normalization for CLAM?

I looked through the paper and didn't see any direct mention of normalizing the stains of the samples before training

Do you guys have any experimental results comparing stain normalization vs no stain normalization?
