### ISSUE TITLE
[F601] dictionary key 'num_workers' repeated with different values

### ISSUE THREAD

**Issue by research-police** [mahmoodlab/CLAM#186]
We patrolled your repo and found the following:
The intended value of `num_workers` is unclear.

https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/utils.py#L47

**Comment by fedshyvana** [comment]
Hey thanks for noting - for any suggestions regarding code refactoring/organization, please feel free to open a PR. Any contribution to improving the code base is always welcome : )
