### ISSUE TITLE
Please do not use star imports

### ISSUE THREAD

**Issue by research-police** [mahmoodlab/CLAM#187]
We patrolled your repo and found the following:

https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/core_utils.py#L3

As the official Python [documentation](https://docs.python.org/3/tutorial/modules.html#:~:text=Note%20that%20in%20general%20the%20practice%20of%20importing%20*%20from%20a%20module%20or%20package%20is%20frowned%20upon%2C%20since%20it%20often%20causes%20poorly%20readable%20code.%20However%2C%20it%20is%20okay%20to%20use%20it%20to%20save%20typing%20in%20interactive%20sessions.) states:

> Note that in general the practice of importing * from a module or package is frowned upon, since it often causes poorly readable code. However, it is okay to use it to save typing in interactive sessions.

In your case, `device` is star imported and used without any hint of origin:
https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/core_utils.py#L118

In other cases, `device` is overwritten in some of the functions:
https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/core_utils.py#L222

**Comment by fedshyvana** [comment]
Hey thanks for noting - for any suggestions regarding code refactoring/organization, please feel free to open a PR. Any contribution to improving the code base is always welcome : )
