### ISSUE TITLE
Function name overwrites built-in function

### ISSUE THREAD

**Issue by research-police** [mahmoodlab/CLAM#188]
We patrolled your repo and found the following:
https://github.com/mahmoodlab/CLAM/blob/9482cbc72df522087cfbaa3e6b52da5207a7980a/utils/eval_utils.py#L48

This obviously overwrites the built-in Python function [eval(...)](https://docs.python.org/3/library/functions.html#eval)
This is especially bad practice, since the overwriting function is star imported (please also refer to #187) and behaves completely different from the built-in function.

**Comment by fedshyvana** [comment]
Hey thanks for noting - for any suggestions regarding code refactoring/organization, please feel free to open a PR. Any contribution to improving the code base is always welcome : )
