### ISSUE TITLE
What are the use of val_num, test_num at dataset.create_splits function?

### ISSUE THREAD

**Issue by pouya1991** [mahmoodlab/CLAM#19]
Hi,
Thank you for publishing your codebase for CLAM. 
I'm trying to use your codebase to evaluate the result on a TCGA dataset, I could do the _creating patches_ and _extracting features_ steps, and now I want to train the model. To split the dataset I want to use _create_splits_seq_ but I don't know which values I must use for _val_num_, _test_num_ in _dataset.create_splits_ function. I couldn't find any documentation on it. 
Thanks.

**Comment by fedshyvana** [comment]
Hi, I hope my response to a previous issue clarifies its usage. See [here](https://github.com/mahmoodlab/CLAM/issues/11).
