### ISSUE TITLE
Conda installation error with PyTorch 

### ISSUE THREAD

**Issue by jonasmrr** [mahmoodlab/CLAM#190]
PROBLEM:
The installation according to the tutorial seems to be broken (Ubuntu 22.04). Creating the conda environment throws the error:

"""
Solving environment: failed

ResolvePackageNotFound: 
  - pytorch==1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0

"""

SOLUTION:
I created a new .yml file that works for me:
[environment.yml.zip](https://github.com/mahmoodlab/CLAM/files/11676818/environment.yml.zip)

**Comment by wwwpeirong** [comment]
Thanks you so much! I encountered the same problem, and solved it by using your new yml file.

**Comment by KidElectric** [comment]
I ran into the same issue -- maybe this should be a PR?

**Comment by yuanzhang7** [comment]
Thank you for sharing your solution！It also helps me.

**Comment by dhlee3342** [comment]
Thank you <3

**Comment by fedshyvana** [comment]
added this to the README, thanks everyone!

**Comment by Shrishtee-kandoi** [comment]
`Solving environment: failed

ResolvePackageNotFound: 
  - libgcc-ng==13.1.0=he5830b7_0`
  
  Any workaround for this one? 
  I used the new .yml file ([environment.yml.zip])

**Comment by MarioPaps** [comment]
Is it possible to use newer versions of CUDA and Pytorch in the .yaml file? These versions are quite old.
