### ISSUE TITLE
Error in plotting heatmap

### ISSUE THREAD

**Issue by dawalisi** [mahmoodlab/CLAM#192]
Here the coords are lists and this statement can only read individual coords
![image](https://github.com/mahmoodlab/CLAM/assets/89849524/1f8b9991-e525-4f6c-ade6-95dd27e6f2c3)
![image](https://github.com/mahmoodlab/CLAM/assets/89849524/719c3205-ed5e-4e29-b8de-1ff71f3fd16c)

**Comment by invisprints** [comment]
I also meet some errors when I run ` CUDA_VISIBLE_DEVICES=0,1 python create_heatmaps.py --config config_template.yaml`.
It says:
```
Traceback (most recent call last):
  File "~/CLAM/create_heatmaps.py", line 371, in <module>
    compute_from_patches(wsi_object=wsi_object, clam_pred=Y_hats[0], model=model, feature_extractor=feature_extractor, batch_size=exp_args.batch_size, **wsi_kwargs,
  File "~/CLAM/vis_utils/heatmap_utils.py", line 77, in compute_from_patches
    A[score_idx] = score2percentile(A[score_idx], ref_scores)
ValueError: could not broadcast input array from shape (195,) into shape (1,)
```
I haven't made any changes to the code and config.

**Comment by vlermakov** [comment]
@invisprints  I had the same issue, and fixed it by changing this one line in heatmap_utils.py: line 23
`def score2percentile(score, ref):
    percentile = percentileofscore(ref.squeeze(), score.squeeze())
    return percentile`

**Comment by hemo0826** [comment]
> @invisprints I had the same issue, and fixed it by changing this one line in heatmap_utils.py: line 23
> 
> def score2percentile(score, ref): percentile = percentileofscore(ref.squeeze(), score.squeeze()) return percentile

![image](https://github.com/mahmoodlab/CLAM/assets/83693017/cec45d1d-d97c-472c-a90d-5ae91fd770f0)
Hello and thank you for your advice! After I changed the code as you suggested, it appears to take up a lot of existing memory when running create_heatmaps! May I ask if you are in the same situation?

**Comment by fedshyvana** [comment]
Hi, it appears you are trying to create the heatmap at a very high resolution. You can change vis_level in the config file to be larger (i.e. lower resolution).
