### ISSUE TITLE
problem about N fold cross validation using create_split_seq.py

### ISSUE THREAD

**Issue by ljhOfGithub** [mahmoodlab/CLAM#197]
![image](https://github.com/mahmoodlab/CLAM/assets/42089575/ebd0b2da-308e-48cc-a6fc-db604db61758)
If I use the command in the graph,I will get ten split files,but there are not enough data in every file,because you set the val_frac and test_frac as 0.1,which will make the portion of the remaining samples are (1-0.1-0.1)*0.75=0.6,losing 20% original data.

**Comment by ShiCrazy** [comment]
You can just assign a value "1" to "label_frac"
