### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by UsamaI000** [mahmoodlab/CLAM#20]
Hi, 
I am trying to run your code. But when I run create_patch.py I get error "division by zero" on line 201 that is -> seg_times /= total
I checked the value for total from line 92-98
mask = df['process'] == 1
process_stack = df[mask]
total = len(process_stack)
seg_times = 0.
patch_times = 0.
stitch_times = 0.
In the csv file value for each entry in column "process" is 0. Kindly, help me with that. And also, Masks which are being saved in Masks folder are same as original images not binary segmented masks. Kindly, help me with that too. 
Thank you

Best Regards

**Comment by fedshyvana** [comment]
Hi, can you tell me what command you used exactly?

Max

**Comment by UsamaI000** [comment]
I used this command

python ./CLAM/create_patches.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 64 --seg --process_list process_list_autogen.csv

This is the error I get
![screenshot](https://user-images.githubusercontent.com/45894162/98837308-a0522680-2464-11eb-82a1-035611444d1c.png)

**Comment by fedshyvana** [comment]
Ok. And are you sure DATA_DIRECTORY contains the whole slide images you
want to process? It should point to a folder of slide image files.

Max

**Comment by UsamaI000** [comment]
Yes I put my images of MoNuSeg data in that folder.

**Comment by fedshyvana** [comment]
Ok. Just to clarify, these are absolute paths in the file system.
DATA_DIRECTORY is just a dummy variable to refer to the path of the folder.
So if your data is stored under for example, ~/data/, that’s what you’ll
specify. If you are sure that you specified the right, can you please print
the output of ls DATA_DIRECTORY? what is the file format of your image
data?

Max

**Comment by UsamaI000** [comment]
Yes, I created folder with DATA_DIRECTORY name and put my images in it which are in .png

**Comment by fedshyvana** [comment]
Ok. Yeah pngs should work. Can you try running the same command without
—process_list xxxxx.csv for now? And see what happens?

Max

**Comment by UsamaI000** [comment]
I ran command

!python ./CLAM/create_patches.py --source data --save_dir results --patch_size 256 --seg 

It ran smoothly 
![Opera Snapshot_2020-11-11_231551_colab research google com](https://user-images.githubusercontent.com/45894162/98848666-e498f300-2473-11eb-9857-331b58fd96ea.png)

But the results getting stored in results/masks folder are same as input image
Input:
![TCGA-DK-A2I6-01A-01-TS1](https://user-images.githubusercontent.com/45894162/98848788-0befc000-2474-11eb-9131-dca35b580648.png)

Mask output:
![TCGA-DK-A2I6-01A-01-TS1](https://user-images.githubusercontent.com/45894162/98848818-16aa5500-2474-11eb-9563-db716610eef5.png)

**Comment by fedshyvana** [comment]
I think in this case it might be because your entire image is “tissue”. So
the whole image gets picked up as segmentation mask.
Try to run patching now and see if it works by using the —patch and —stitch
command

**Comment by UsamaI000** [comment]
I ran this command 

!python ./CLAM/create_patches.py --source "./data" --save_dir "./results" --patch_size 256 --seg --patch --stitch

I get an error:

OUTPUT:
progress: 0.00, 0/6
processing TCGA-AR-A1AK-01Z-00-DX1.png
Creating patches for:  TCGA-AR-A1AK-01Z-00-DX1 ...
Traceback (most recent call last):
  File "./CLAM/create_patches.py", line 294, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "./CLAM/create_patches.py", line 188, in seg_and_patch
    heatmap, stitch_time_elapsed = stitching(file_path, downscale=64)
  File "./CLAM/create_patches.py", line 14, in stitching
    heatmap = StitchPatches(file_path, downscale=downscale, bg_color=(0,0,0), alpha=-1, draw_grid=False)
  File "/content/CLAM/wsi_core/WholeSlideImage.py", line 46, in StitchPatches
    file = h5py.File(hdf5_file_path, 'r')
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './results/patches/TCGA-AR-A1AK-01Z-00-DX1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Then I tried running the same command without --stitch
!python ./CLAM/create_patches.py --source "./data" --save_dir "./results" --patch_size 256 --seg --patch 

It ran smoothly

OUTPUT:
progress: 0.00, 0/6
processing TCGA-AR-A1AK-01Z-00-DX1.png
Creating patches for:  TCGA-AR-A1AK-01Z-00-DX1 ...
segmentation took 0.11063313484191895 seconds
patching took 6.151199340820312e-05 seconds
stitching took -1 seconds


progress: 0.17, 1/6
processing TCGA-AR-A1AS-01Z-00-DX1.png
Creating patches for:  TCGA-AR-A1AS-01Z-00-DX1 ...
segmentation took 0.10430741310119629 seconds
patching took 4.553794860839844e-05 seconds
stitching took -1 seconds


progress: 0.33, 2/6
processing TCGA-AY-A8YK-01A-01-TS1.png
Creating patches for:  TCGA-AY-A8YK-01A-01-TS1 ...
segmentation took 0.10186004638671875 seconds
patching took 4.410743713378906e-05 seconds
stitching took -1 seconds


progress: 0.50, 3/6
processing TCGA-G9-6336-01Z-00-DX1.png
Creating patches for:  TCGA-G9-6336-01Z-00-DX1 ...
segmentation took 0.09743165969848633 seconds
patching took 9.393692016601562e-05 seconds
stitching took -1 seconds

But even after this their is nothing being saved in my patches folder. There should be patches saved in .h5 format.

**Comment by fedshyvana** [comment]
I see. Yeah I think this is likely a issue with the segmentation such that
it’s not correctly recognizing your patches as tissue. There could be some
funny thing going on because I only tested this code on whole slide images.
If you share with me some example images from your dataset I can look into
the issue more closely.

Max

**Comment by UsamaI000** [comment]
Sure. Can you share your email with me ?

**Comment by UsamaI000** [comment]
Also, I am thinking of using this code and checking its result on thick blood malaria slides. What do you think about that. Can it be used efficiently? Because in your paper you mentioned that you tested on cellphone microscopy images for which results were very good considering the model was trained on WSI

**Comment by fedshyvana** [comment]
Oh wait I think I know what the issue is. I think it’s because the default
segmentation algorithm assumes that your tissue is of a certain area
(typically in large whole slides, tissue regions are large, and small
regions are often artifacts).

In your case, if you use one of the preset .csv files and set the tissue
area parameter to 0. It would probably work normally.

Max

**Comment by UsamaI000** [comment]
I'll try that

**Comment by UsamaI000** [comment]
Hi,
I did what you advised it is segmenting but result are still weird. 

![62fd1d15-f864-4f37-b181-ed34398cf2ac](https://user-images.githubusercontent.com/45894162/98854280-2af25000-247c-11eb-8ec6-6c3795c79952.png)

Also, stitching gives weird result

![FieldPos004_EDOF_RGB](https://user-images.githubusercontent.com/45894162/98854363-44939780-247c-11eb-9d28-5f3bb40cad19.png)

If you could contact me on my email it would be of great help. Also, provide me your email.
Email: usama.irfan@itu.edu.pk
