### ISSUE TITLE
HeatMap

### ISSUE THREAD

**Issue by wxyz-wjx** [mahmoodlab/CLAM#200]
How to find the coordinates of those areas with high attention scores, how to do the demonstration of the left is the original image, the right is the heat map at the same time view function？

**Comment by fedshyvana** [comment]
The attention scores + coordinates should be saved as .h5s when you generate the heatmap which you can analyze to extract high attention regions. I believe the demonstration is built using OpenSeaDragon by a software engineer and unfortunately we not have a clean module that you plug and play.
