### ISSUE TITLE
How to set the "step_size" Parameter in create_patches.py or create_patches_fp.py?

### ISSUE THREAD

**Issue by ShiCrazy** [mahmoodlab/CLAM#201]
I have previously set the step_size to 0, ensuring that there is no overlap between different tiles. However, I am now considering whether it would be beneficial to adjust the step_size setting. I would like to ask the author or anyone else if they have good experience with setting this parameter. Thank you to everyone who has contributed to this repository!

**Comment by fedshyvana** [comment]
I believe the default is to set the step_size = patch_size so there's no overlap between patches. I have not experienced with any other patch sizes, mostly because decreasing the patch_size (i.e. increasing overlap) will lead to increasing computational cost/memory requirement quadratically.
