### ISSUE TITLE
difference among seg_level, patch_level and custom_downsample about TCGA-BRCA

### ISSUE THREAD

**Issue by ljhOfGithub** [mahmoodlab/CLAM#207]
If I want to extract features of patches in TCGA-BRCA at 20x magnification, how should I set parameters in create_patches_fp and extract_features_fp?

**Comment by ljhOfGithub** [comment]
How can I get the type of scanner?

**Comment by ljhOfGithub** [comment]
> How can I get the type of scanner?我怎样才能获得扫描仪的类型？

I know.Use the wsi.properties to get the dict.

**Comment by ljhOfGithub** [comment]
> If I want to extract features of patches in TCGA-BRCA at 20x magnification, how should I set parameters in create_patches_fp and extract_features_fp?如果我想在TCGA-BRCA中以20倍放大率提取斑块的特征，我应该如何设置create_patches_fp和extract_features_fp中的参数？

See https://github.com/mahmoodlab/CLAM/issues/115

**Comment by syy-create** [comment]
您好，关于您如何利用create_patches_fp获得20x视野,您的解决办法是设置level=0，patches=512，以获得40x视野，之后利用custom_downsample=2来获得20x视野吗？还是说有其他方法可以直接获得20x视野的patch，期待你的回复，谢谢。

**Comment by ljhOfGithub** [comment]
应该是的，因为原本tcga数据集的wsi默认的放大倍数AppMag都是40x，按照这里的说法（作者也肯定了）https://github.com/mahmoodlab/CLAM/issues/115，你的理解应该是对的，记得step_size也是512

**Comment by syy-create** [comment]
你好，非常感谢你的回复。我最近刚尝试这方面的工作。还有几个问题想要了解。1、请问你是否清楚为什么不直接获取20x视野的patches呢？是因为直接level设置，不容易得到合适的视野吗？
2、step_size和patch_size的大小是不是要最好保持一致呀
3、就是我看到好多人提到了wsi这个类，请问这个类是openslide的类吗？
再次感谢。
&nbsp;


^^^^^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月29日(星期三) 下午4:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mahmoodlab/CLAM] difference among seg_level, patch_level and custom_downsample about TCGA-BRCA (Issue #207)





 
应该是的，因为原本tcga数据集的wsi默认的放大倍数AppMag都是40x，按照这里的说法（作者也肯定了）https://github.com/mahmoodlab/CLAM/issues/115，你的理解应该是对的，记得step_size也是512

**Comment by weiaicunzai** [comment]
> 你好，非常感谢你的回复。我最近刚尝试这方面的工作。还有几个问题想要了解。1、请问你是否清楚为什么不直接获取20x视野的patches呢？是因为直接level设置，不容易得到合适的视野吗？ 2、step_size和patch_size的大小是不是要最好保持一致呀 3、就是我看到好多人提到了wsi这个类，请问这个类是openslide的类吗？ 再次感谢。 &nbsp; ^^^^^^ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月29日(星期三) 下午4:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mahmoodlab/CLAM] difference among seg_level, patch_level and custom_downsample about TCGA-BRCA (Issue #207) 应该是的，因为原本tcga数据集的wsi默认的放大倍数AppMag都是40x，按照这里的说法（作者也肯定了）#115，你的理解应该是对的，记得step_size也是512 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

有时候整个病理图像svs文件里没有20x得扫描，只有40x的。
