### ISSUE TITLE
How to set the parameters when converting from 40X WSI to 20X WSI

### ISSUE THREAD

**Issue by YinZhe0412** [mahmoodlab/CLAM#208]
Hello，
I recently encountered an issue while running CLAM. Most WSIs are 20x, so I want to handle 40x WSIs by changing the parameter format. 
1. I read the 151st and 163rd issues but don't know what they mean. Does "level" refer to "seg_level" and "vis_level"? 
Do patch_size and step_size need to be modified?
2. Running create_patches_ fp.py input parameter file seg_ Level and vis_level are all -1, but the display in the resulting process_ list_autogen.csv is 2.

Looking forward to your reply！

**Comment by LiuJin629** [comment]
I have the same question!
