### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by AnitaGoro** [mahmoodlab/CLAM#209]
I am using CLAM to classify 245 WSI into 2 classes, MSI-H and MSS. I have 112 MSI-H WSI and 133 MSS. All WSI are scanned at 40x magnification and I patched them at level 0 in order to carry out the feature extraction. I modified the main.py script in order to use te task_2_tumor_subtyping. The settings I use are the following: 

{'num_splits': 10, 'k_start': -1, 'k_end': -1, 'task': 'task_2_tumor_subtyping', 'max_epochs': 200, 'results_dir': './results', 'lr': 0.0002, 'experiment': 'task_2_tumor_subtyping_CLAM_50', 'reg': 1e-05, 'label_frac': 1.0, 'bag_loss': 'ce', 'seed': 1, 'model_type': 'clam_sb', 'model_size': 'small', 'use_drop_out': True, 'weighted_sample': True, 'opt': 'adam', 'bag_weight': 0.7, 'inst_loss': 'svm', 'B': 8, 'split_dir': 'splits/task_2_tumor_subtyping_100'}

However, I am not achieving good results.

<img width="932" alt="Captura de Pantalla 2023-10-10 a la(s) 23 57 46" src="https://github.com/mahmoodlab/CLAM/assets/144285841/876c6272-963c-439f-a4a7-427a24cf7d13">

All our WSI were approved by a pathologist and therefore we do not think that they are the source of our problem. 
Do you have any ideas on how could we improve our performance?
Thank you very much!

**Comment by fedshyvana** [comment]
Hey, you could maybe look into using more state of the art SSL pretrained encoder models such as ctranspath https://github.com/Xiyue-Wang/TransPath. The ImageNet transfer ResNet50 used in this repo is quite outdated from SOTA.
