### ISSUE TITLE
run eval.py get TypeError

### ISSUE THREAD

**Issue by TinnyFlames** [mahmoodlab/CLAM#21]
Hi! Thank you for publishing such grate work.
I have encountered an error during **run  python eval.py**  in my own dataset
Here is the error message:
```
Traceback (most recent call last):
  File "eval.py", line 134, in <module>
    model, patient_results, test_error, auc, df  = eval(split_dataset, args, ckpt_paths[ckpt_idx])
  File "/home/pch/Documents/hx/CLAM/utils/eval_utils.py", line 53, in eval
    patient_results, test_error, auc, df, _ = summary(model, loader, args)
  File "/home/pch/Documents/hx/CLAM/utils/eval_utils.py", line 70, in summary
    for batch_idx, (data, label) in enumerate(loader):
  File "/home/pch/anaconda3/envs/clam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/pch/anaconda3/envs/clam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/pch/anaconda3/envs/clam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pch/anaconda3/envs/clam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pch/anaconda3/envs/clam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/pch/Documents/hx/CLAM/utils/utils.py", line 36, in collate_MIL
    img = torch.cat([item[0] for item in batch], dim = 0)
TypeError: expected Tensor as element 0 in argument 0, but got str
```

**Here is the command I used:**
CUDA_VISIBLE_DEVICES=1 python eval.py --drop_out --k 10 --models_exp_code tcga_hx_cv_sb_s1 --save_exp_code eval_tcga_hx_cv_sb_s1 --task tcga_hx_cv --model_type clam_sb --results_dir results --data_root_dir dataset/hx_resnet_feature

the Dir structure is as follows:
![image](https://user-images.githubusercontent.com/24524613/99406353-c118f100-2928-11eb-801e-ae14829dff05.png)
![image](https://user-images.githubusercontent.com/24524613/99406430-d55cee00-2928-11eb-85bc-0ae5c18f85f4.png)

I am little bit confused why I get str error, can you suggest where may be wrong?
Thank you!

**Comment by fedshyvana** [comment]
Hi, it's unclear to me what the issue is based on what you just showed me, I think the issue is likely with how you defined the task/csv file, can you show me how you defined the "tcga_hx_cv" task, and what does the csv file look like?

**Comment by TinnyFlames** [comment]
> Hi, it's unclear to me what the issue is based on what you just showed me, I think the issue is likely with how you defined the task/csv file, can you show me how you defined the "tcga_hx_cv" task, and what does the csv file look like?

**The tcga_hx.csv  is defined as follows**
![image](https://user-images.githubusercontent.com/24524613/99487898-3a085f00-29a2-11eb-8c78-732be2918658.png)
**The task defined in eval.py is**
![image](https://user-images.githubusercontent.com/24524613/99489852-96b84980-29a3-11eb-979c-a7c060072285.png)

**And the task defined in main.py is**
![image](https://user-images.githubusercontent.com/24524613/99489120-1e518880-29a3-11eb-8e0d-2c29fda89396.png)

**Comment by TinnyFlames** [comment]
The problem has been solved!  I misused the class **WSI_Classification...**  
lol
Thanks for your response!

**Comment by siemdejong** [comment]
The next thing I tried solved the issue: `data_root_dir` was `None`. Forgot to pass it as command argument.
