### ISSUE TITLE
".ndpi" type WSI

### ISSUE THREAD

**Issue by LiuJin629** [mahmoodlab/CLAM#210]
My whole slides' type is ".ndpi", could I use this pipeline to patch my whole slides?

**Comment by Wan-Jiayu** [comment]
@LiuJin629 Hello!May I ask if you have successfully used this code to patch WSIs with ‘.ndpi’ suffix?

**Comment by LiuJin629** [comment]
@Wan-Jiayu 你好，并没有，我在使用CLAM切ndpi的病理片子时，发现clam的切图并不能准确识别到ndpi中的组织区域(切是可以切，但是这样切出来有很多非组织区域的杂图。在我使用svs时该clam切图代码可以准确识别到组织区域，也就是切图的结果中，绿色的框框可以精准框出组织，而ndpi的片子会生成一个绿色的大框将整个病理片子都框起来)，所以我切ndpi片子时还是存在问题的

**Comment by Wan-Jiayu** [comment]
@LiuJin629 我今天尝试了一下切ndpi后缀的WSI，并且成功了，我并没有遇到你说的这些问题，我切出来的效果还不错
![image](https://github.com/mahmoodlab/CLAM/assets/100431658/2aad61d4-c679-4387-8b43-ebf3e965d143)

**Comment by LiuJin629** [comment]
@Wan-Jiayu 确实哎，你切的没有问题，我切ndpi时绿色框把全部wsi都框出来了。还有个问题，clam现在切图切出来后的那个hdf5文件中是不是存的不是实际的patch，而是patch的在wsi上的坐标呀
