### ISSUE TITLE
Some WSI cannot be segmented

### ISSUE THREAD

**Issue by Ysc-shark** [mahmoodlab/CLAM#214]
I am using the CLAM for segmenting ovarian cancer WSI images, utilizing parameters from the bwh_biopsy.csv file. However, I am encountering issues with two types of WSI images: those with very faint colors and those containing several sections within a single image. How can I resolve these issues?
![39872_thumbnail](https://github.com/mahmoodlab/CLAM/assets/85819178/0a332d00-dbba-42b7-9eee-2914f982f9fd)

![1660_thumbnail](https://github.com/mahmoodlab/CLAM/assets/85819178/63e09d20-a254-4399-8084-7db80a999561)

**Comment by scjjb** [comment]
My suggestion would be to try reducing sthresh (the saturation threshold used, lower means less saturation needed to be considered as tissue) until you start to get what you want, if this doesn't work play around with mthresh and use_otsu
