### ISSUE TITLE
Failed to install using clam.yaml due to conflicts

### ISSUE THREAD

**Issue by l-cli** [mahmoodlab/CLAM#216]
Hello! I used the steps described in the [installation guide](https://github.com/mahmoodlab/CLAM/blob/26e0b6c4873e112f1ccd74cd834894c4ab7a2934/docs/INSTALLATION.md) to install CLAM; the first attempt generated the error message below:
```
Solving environment: failed
ResolvePackageNotFound: 
  - pytorch==1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
```

I then moved pytorch under -pip in the .yaml file and did a second attempt, but multiple conflicts were found and the environment failed to be created. The specific conflicts are in this file as it is too long to be pasted in this message: 
[UnsatisfiableError.txt](https://github.com/mahmoodlab/CLAM/files/13548960/UnsatisfiableError.txt)

Could someone help check and see what might be wrong here? Thank you!

**Comment by jordivea-odap** [comment]
Hi, I have the same issue with that package. Have you solved it?

**Comment by spencerkrichevsky** [comment]
https://github.com/mahmoodlab/CLAM/issues/190

This worked for me and others
