### ISSUE TITLE
Threshold adjustment in preprocessing stage

### ISSUE THREAD

**Issue by ACNicotine** [mahmoodlab/CLAM#218]
How to adjust the thresholds according to different datasets so that the preprocessing part can correctly segment the tissue without segmenting some other segments (such as handwriting, contamination). I don’t know how to set the various thresholds in HSV space.

**Comment by fedshyvana** [comment]
hey yeah unfortunately currently if you want to also filter out e.g. handwriting/slide artefacts based on thresholding alone using the included workflow, it may not be possible.
