### ISSUE TITLE
Format of h5 files

### ISSUE THREAD

**Issue by samkleeman1** [mahmoodlab/CLAM#22]
Many thanks for making this incredible repository. I am hoping to use tiles that I have pre-generated, as we have pathologist-defined tumor annotations. I am slightly unclear how to convert the tiles including the h5/pt file formats you are using as input. Are you able to provide any advice on this? Kind regards, Sam Kleeman, PhD Student Cold Spring Harbor Laboratory.

**Comment by fedshyvana** [comment]
Hi Sam, sorry I am not totally clear about your question, are you saying you already have the tiles (presumably stored in some standard image format like .jpg or .png) and are wondering how you might generate h5/pt files used as inputs to training a model? 
Max

**Comment by samkleeman1** [comment]
My apologies for the delay in answering this, I had not seen your response. Yes your question is correct, I have already generated the tiles for my cohort in JPG format, and I am wondering how to use these as input. This is necessary as the slide images and the annotations are in pretty strange formats at present.

**Comment by fedshyvana** [comment]
Hi Sam, so whichever way you think is easier for you, but basically, in my pipeline, I generate one .h5 file per slide, where it contains two fields: 
1. 'img' - which is the array of tiles extracted from that slide (shape N x h x w x c) 
2. 'coords' - which is the array of x,y coordinates corresponding the tiles (shape N x 2)
N is the number of tiles in the slide, h x w are tile dimensions, and c being number of channels (e.g. 3 for RGB). 
If you can convert your jpg tiles into one .h5 file per slide, then you would be able to use "extract_features.py" in the code base to perform feature extraction, and all subsequent steps for training and evaluation. 

To verify that your .h5 files are prepared correctly, you should be able to load the .h5 and verify that the printed shape for the coordinates and tiles are correct, for example:
import h5py
with h5py.File(PATH_TO_FILE,'r') as hdf5_file:
	img = hdf5_file['imgs'][:]
	coord = hdf5_file['coords'][:]
        print(img.shape)
        print(coord.shape)
