### ISSUE TITLE
Seeking Advice: Low Accuracy in CLAM Training on CAMELYON16 Dataset

### ISSUE THREAD

**Issue by ACNicotine** [mahmoodlab/CLAM#220]
Hello, thank you for your excellent work. However, I encountered a problem when using CLAM to train the CAMELYON16 dataset: Initially, I trained the TCGA dataset using your code, and the results were very good. But when I trained the CAMELYON16 dataset with the same parameters, the accuracy was only 80%. However, I downloaded the model you provided and found that its accuracy on CAMELYON16 reached 95%. This result makes me certain that the issue is not with image preprocessing. So, may I ask if there are any training tips specific to the CAMELYON16 dataset? What I have already tried includes: increasing the number of training rounds, using CLAM_SB and CLAM_MB, and using both small and big parameters, but none of these have improved the results.

**Comment by fedshyvana** [comment]
Hi sorry I missed this, you could maybe look into using more state of the art SSL pretrained encoder models such as ctranspath https://github.com/Xiyue-Wang/TransPath. The ImageNet transfer ResNet50 used in this repo is quite outdated from SOTA at this point if you're goal is to optimize performance.
