### ISSUE TITLE
What data types can be processed

### ISSUE THREAD

**Issue by syy-create** [mahmoodlab/CLAM#222]
Hello, may I ask for your file create_ Patches_ Fp, when processing images, in addition to being able to handle files in SVS format, it can also handle several types of files

**Comment by fedshyvana** [comment]
Any WSI formats supported by openslide should be fair game, this includes things like some types of tiff, .ndpi, .mrxs, etc.

**Comment by syy-create** [comment]
Thank you for your answer. I would also like to ask you a question about parameters in process_list.autogen.csv.
The effect is very good when slicing using createPatches'fp.py. But when I switch to other types of slices, such as TIF or NDPI, the effect may deteriorate. I have reviewed the previous issues and found that it is necessary to adjust the parameters of process_list.autogen.csv to improve the quality of slicing. But I have some doubts about some parameters in the table. Can you explain in detail the meaning of the parameters in this CSV table? What other parameters should be adjusted to improve slice quality?






^^^^^^
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mahmoodlab/CLAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 凌晨0:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mahmoodlab/CLAM] What data types can be processed (Issue #222)





 
Any WSI formats supported by openslide should be fair game, this includes things like some types of tiff, .ndpi, .mrxs, etc.

**Comment by syy-create** [comment]
> Thank you for your answer. I would also like to ask you a question about parameters in process_list.autogen.csv. The effect is very good when slicing using createPatches'fp.py. But when I switch to other types of slices, such as TIF or NDPI, the effect may deteriorate. I have reviewed the previous issues and found that it is necessary to adjust the parameters of process_list.autogen.csv to improve the quality of slicing. But I have some doubts about some parameters in the table. Can you explain in detail the meaning of the parameters in this CSV table? What other parameters should be adjusted to improve slice quality? ^^^^^^ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mahmoodlab/CLAM" ***@***.***&gt;; 发送时间:&nbsp;2024年2月29日(星期四) 凌晨0:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mahmoodlab/CLAM] What data types can be processed (Issue #222) Any WSI formats supported by openslide should be fair game, this includes things like some types of tiff, .ndpi, .mrxs, etc. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![B`8V_%HZ7{M3Q7EX)7 4{{K](https://github.com/mahmoodlab/CLAM/assets/59799671/27109dfd-d409-4991-be2b-a7f425c33d67)

**Comment by fedshyvana** [comment]
Hi, you can refer to [custom-default-segmentation-parameters](https://github.com/mahmoodlab/CLAM?tab=readme-ov-file#custom-default-segmentation-parameters) for explanation of key parameters. Feel free to follow-up if you have specific questions.
