### ISSUE TITLE
Some artifacts are identified as tissue regions

### ISSUE THREAD

**Issue by huha149** [mahmoodlab/CLAM#223]
When I segment the TCGA data, there will be some artifacts that are identified as tissue regions, and thus divided into patches. How can I fix it.
![1](https://github.com/mahmoodlab/CLAM/assets/147480747/56e5f4ad-f8ec-424c-84a0-b968581c0542)
![HE](https://github.com/mahmoodlab/CLAM/assets/147480747/2b70d29d-1cc2-436e-b765-7bc0271b4953)

![HE](https://github.com/mahmoodlab/CLAM/assets/147480747/5decc172-e1ac-4407-bb46-052692f7dd27)

**Comment by fedshyvana** [comment]
Hi, unfortunately this is a limitation of the current segmentation pipeline. You could try maybe adjusting the area threashold go be higher (which will get rid of small artefacts but also potentially smaller pieces of tissue). Although I think in practice, MIL algorithms are pretty robust to artifacts by learning to attend to informative regions (as long as artifacts are not correlated with disease labels).

**Comment by huha149** [comment]
Thanks for replying and have a good life
