### ISSUE TITLE
Many Nan values in the extracted feature

### ISSUE THREAD

**Issue by folkaholic** [mahmoodlab/CLAM#225]
Hello there, thanks for sharing this useful tool.
I have encounter a problem, I downloaded, patched, and extracted the feature of the TCGA dataset as told by the instruction. I checked the mask files which are normal, but I found there are so many Nan and inf values in the pt_files. Does anyone has similar problems? Thank you.

**Comment by fedshyvana** [comment]
do you have example data for reproducing this issue?

**Comment by eternalld** [comment]
I also encountered this problem, is there a solution now?

**Comment by eternalld** [comment]
> do you have example data for reproducing this issue?

We use liver cancer pathological images from the TCGA database, for example, the file name is "TCGA-2Y-A9HB-01Z-00-DX1.ECF68E86-4D45-4545-A1D2-184D5ED38C3C"

**Comment by eternalld** [comment]
Sometimes I encounter an error when executing feature extract_fp.py: "openslide.lowlevel.OpenSlideError: Corrupt JPEG data: premature end of data segment", but when I use Qupath to open the file I find that the svs image can be opened normally. Have you ever encountered this situation?

**Comment by fedshyvana** [comment]
I think i saw another post saying they changed the torch version and it was fixed. I recently bumped all the package dependencies to be much more up to date, could you give it a try to see if it solves your issue?

**Comment by eternalld** [comment]
okok，I'll try it.



---Original---
From: "Max ***@***.***&gt;
Date: Tue, Apr 9, 2024 12:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mahmoodlab/CLAM] Many Nan values in the extracted feature (Issue#225)




 
Regarding NaNs, I think i saw another post saying they changed the torch version and it was fixed. I recently bumped all the package dependencies to be much more up to date, could you give it a try to see if it solves your issue?

**Comment by fedshyvana** [comment]
please let me know / re-open if you experience further issues on this, thanks
