### ISSUE TITLE
Is this repo compatible with Windows operating system?

### ISSUE THREAD

**Issue by jiajundeng** [mahmoodlab/CLAM#23]
Hi, many thanks for your outstanding work. I would like to know if this repo compatible with windows?

Best,
Jiajun

**Comment by fedshyvana** [comment]
Hi, I have only tested it on Linux. Unfortunately, I do not have a windows machine on which to test its compatibility. I believe all the packages used in the repository are available on windows so in theory it should work. Although there might be small tweaks you have to do to get it to work smoothly. 

Max
