### ISSUE TITLE
About parameters in process_list.autogen.csv

### ISSUE THREAD

**Issue by syy-create** [mahmoodlab/CLAM#231]
The effect is very good when slicing using createPatches'fp.py. But when I switch to other types of slices, such as TIF or NDPI, the effect may deteriorate. I have reviewed the previous issues and found that it is necessary to adjust the parameters of process_list.autogen.csv to improve the quality of slicing.  What other parameters should be adjusted to improve slice quality?
![B`8V_%HZ7{M3Q7EX)7 4{{K](https://github.com/mahmoodlab/CLAM/assets/59799671/920b4cdf-55e9-45dc-9697-c027dd0a9679)

**Comment by fedshyvana** [comment]
Hi, you can refer to [custom-default-segmentation-parameters](https://github.com/mahmoodlab/CLAM?tab=readme-ov-file#custom-default-segmentation-parameters) for explanation of key parameters.
