### ISSUE TITLE
Unable to import 'datasets.dataset_generic'

### ISSUE THREAD

**Issue by gusSCIMOV** [mahmoodlab/CLAM#236]
HI, 

I'm trying the latest release and UNI pretrained weights. Recently, I've been experiencing this issue creating splits:
File "/app/Codebase/_Pancreas/Histology/MIL_framework/CLAM2/create_splits_seq.py", line 4, in <module>
    from datasets.dataset_generic import Generic_WSI_Classification_Dataset, Generic_MIL_Dataset, save_splits
ModuleNotFoundError: No module named 'datasets.dataset_generic'

I tried downgrading 'dataset' until 2023's versions but at end resulting useless for addressing that issue. I haven't had this problem before.
Thank you so much.

**Comment by fedshyvana** [comment]
Should be fixed now!
