### ISSUE TITLE
Segmentation parameters for WSI with partially black background 

### ISSUE THREAD

**Issue by Fel1xJulian** [mahmoodlab/CLAM#242]
Hi, 

is there a set of ready-to-use segmentation parameters available that successfully segments WSIs with a partially black background? Right now the mask is right at the border between black and light pixels. 
The black background is a result of the necessary conversion from czi to tiff. 

<img width="1401" alt="Screenshot 2024-04-22 at 12 04 36" src="https://github.com/mahmoodlab/CLAM/assets/78545317/7f1551da-5364-4816-8310-d59dd136a699">

**Comment by antalaszek** [comment]
@Fel1xJulian How did you solve this issue?
