### ISSUE TITLE
Datasets in configuration file and GPU Training Step

### ISSUE THREAD

**Issue by rohith2011** [mahmoodlab/CLAM#245]
I have used the .tif files (I have manually converted the each frame of the .scn format and saved them within the range of 1xe8 constrain of the data) then I have created the patches using the preset of bwh_biopsy.csv.

Then I have followed the steps to extract the features form this data. Then I have worked and set up the DATA_ROOT_DIR for both the classes ("task_1_tumor_vs_normal").

When I setup the data_dir file directory in the 
`if args.task == 'task_1_tumor_vs_normal':
    args.n_classes=2
    dataset = Generic_MIL_Dataset(csv_path = 'dataset_csv/tumor_vs_normal_dummy_clean.csv',
                            data_dir= os.path.join(args.data_root_dir, 'tumor_vs_normal_feat_resnet'),
                            shuffle = False, 
                            seed = args.seed, 
                            print_info = True,
                            label_dict = {'normal_tissue':0, 'tumor_tissue':1},
                            label_col = 'label',
                            ignore=[])`

the directory should be that of the `
DATA_ROOT_DIR/
    ├──DATASET_1_DATA_DIR/
        ├── h5_files
                ├── slide_1.h5
                ├── slide_2.h5
                └── ...
        └── pt_files
                ├── slide_1.pt
                ├── slide_2.pt
                └── ...
    ├──DATASET_2_DATA_DIR/
        ├── h5_files
                ├── slide_a.h5
                ├── slide_b.h5
                └── ...
        └── pt_files
                ├── slide_a.pt
                ├── slide_b.pt
                └── ...
    └──DATASET_3_DATA_DIR/
        ├── h5_files
                ├── slide_i.h5
                ├── slide_ii.h5
                └── ...
        └── pt_files
                ├── slide_i.pt
                ├── slide_ii.pt
                └── ...
    └── ...`

I put this as the directory for the data_dir arg in the command above.

Below is the error I am getting. 

FileNotFoundError: [Errno 2] No such file or directory: 'DATA_ROOT_DIR/FEATURES_DIRECTORY/pt_files/O3594401.scn - Series 2.ome.pt'

How can this be the error solve this as the directory should be like "DATA_ROOT_DIR" insted of "DATA_ROOT_DIR/FEATURES_DIRECTORY/pt_files/" 

The PC configuration:-

OS-Linux
GPU: A100 Nvidia

**Comment by fedshyvana** [comment]
Hi, sorry for the late response, this sounds like you can just set the path to FEATURES_DIRECTORY as your "data_root_dir" instead? Let me know if you are still having issues.
