### ISSUE TITLE
expand sdpc format

### ISSUE THREAD

**Issue by lingxitong** [mahmoodlab/CLAM#249]
hello,CLAM now is the universe tools for wsi preprocess，but sdpc format wsi is not support，sdpc is a wsi format has better quality，you can see in https://120.78.213.120/home，I want to expand this format,can I pull request?I will send 2 sdpc format wsi so that you can test the code I expand.Thanks

**Comment by lingxitong** [comment]
> Hi, I'd like to use CLAM to process WSI, but the file format is sdpc. Could you share the code preprocessing sdpc format file with me? Thanks!

see https://github.com/lingxitong/MIL_BASELINE

**Comment by fedshyvana** [comment]
Hi @lingxitong, thank you so much for your awesome work, and my apology for not getting to this much sooner. Pull requests / contributions are always welcome!
