### ISSUE TITLE
Color Issue in Heatmap File C3L-01663-21_0.75_roi_0_blur_0_rs_1_bc_0_a_0.4_l_1_bi_0_0.2.jpg in heatmap_production_results\HEATMAP_OUTPUT\LSCC Folder

### ISSUE THREAD

**Issue by apple5413** [mahmoodlab/CLAM#251]
Dear CLAM Developer,

I have been using the WSI from CLAM-master\CLAM-master\heatmaps\demo\slides and the checkpoint file s_0_checkpoint.pt from CLAM-master\CLAM-master\heatmaps\demo\ckpts to generate heatmaps. However, I noticed that the heatmap for the file C3L-01663-21_0.75_roi_0_blur_0_rs_1_bc_0_a_0.4_l_1_bi_0_0.2.jpg in the heatmap_production_results\HEATMAP_OUTPUT\LSCC folder is predominantly blue, indicating low attention, and lacks the colors corresponding to high attention. Could you please help me understand the cause of this issue? Could it be related to the parameters I used?
![(screenshot) C3L-01663-21_0 75_roi_0_blur_0_rs_1_bc_0_a_0 4_l_1_bi_0_0 2](https://github.com/mahmoodlab/CLAM/assets/155521932/5d0acda0-43d5-45e1-b7e5-b1090931ac68)

**Comment by fedshyvana** [comment]
Hi, sorry for the late response, hopefully you already resolved the issue. If not, please feel free to follow-up with more context and I will try to address this week.
