### ISSUE TITLE
Attention maps for multiple predictions

### ISSUE THREAD

**Issue by otto863** [mahmoodlab/CLAM#256]
Hello,
I trained a model for classification using slide-level labels. For my PhD project, I would like to have CLAM return attention maps for both prediction 1 and 2. Is there a easy way to adapt the script(s) to achieve this? 
Thanks a lot for your help!

**Comment by fedshyvana** [comment]
If you're using CLAM_SB there should just be one set of attention scores for each slide, but it's always interpreted as the attention for that particular slide / class.
