### ISSUE TITLE
About the custom_downsample parameter in extract_feature_fp.py

### ISSUE THREAD

**Issue by H-Q-N** [mahmoodlab/CLAM#259]
In old_CLAM, I can achieve the x20 magnification effect by using 
```
patch_level=0——x40
custom_downsample=2
```
Here is the code I used in the old version for create_patches_fp.py and extract_feature_fp.py respectively:
```
python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --seg --patch --stitch --preset tcga.csv
CUDA_VISIBLE_DEVICES=0 python extract_features_fp.py --data_h5_dir DIR_TO_COORDS --data_slide_dir DATA_DIRECTORY --csv_path CSV_FILE_NAME --feat_dir FEATURES_DIRECTORY --batch_size 512 --slide_ext .svs --custom_downsample 2
```
But in new_CLAM, target_patch_size is set to 224, and custom_downsample is deleted. How to achieve the x20 effect?
The TCGA database is used：
```
 patch_level=0——x40, 
 patch_level=1——x10
```

**Comment by fedshyvana** [comment]
If you want 20x at 256 by 256 patches, I think you would patch at level 0 with patch size of 512 for create_patches_fp.py, and then you can set target_patch_size to 256 when running extract_features_fp.py. Hope that helps!
