### ISSUE TITLE
For two classes case, what is the purpose of second classifier in the CLAM_SB with same data as input.

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [mahmoodlab/CLAM#26]
Hi Again,

I have one more question. I got confused after going deeper in the script.

The problem statement I have is given slide labels [0 (negative) and 1 (positive)], I want to generate pseudo labels based on attention scores.
Now the number of classes as per the script : n_classes = 2 for camelyon data set
based on this information the Clam_SB creates two classifier branches  [line 92 in model_clam.py]. Following on this, at line 165 in the same script, the instance classifier is looped based on the number of classes. The instance label when equals 1 then instance loss is computed. However, the doubt I have is why two classifier is required when instance loss is calculated only when instance label is 1.
For example, say I have positive slide [which contains lesion and normal]
now from the slide level label I will mark each instance as positive, which is fed in first classifier out of two and then picking most attended and least attended tiles to classify.
I don't get why do we feed the same data and info into second classifier.

Am I understanding it wrong?
thanks in advance

**Comment by fedshyvana** [comment]
Hi, i agree that having 2 separate classifiers for a 2 class-problem might seem redundant in the context of a 2 class tumor vs normal problem. However, this is not always the case. For example, suppose the 2-class problem is subtyping Adenocarcinoma vs. Squamous Cell, at the slide-level we have 2 classes but at the patch-level we technically have more than 2 classes, e.g. there's adeno, squamous and normal tissue. Therefore, in this case, we have 2 instance-level classifiers where each classifier predicts whether a patch belongs to that patch or not (one-vs-rest). So for ease of making the model generalizable to all kinds of problems, I have set the number of instance-level classifiers to always be the same as the number of classes, and each classifier considers a binary one vs. rest problem. If you wish to discuss further, you are also welcome to email me at mingyanglu1997@gmail.com.
