### ISSUE TITLE
model types 'clam_sb', 'clam_mb', 'mil'

### ISSUE THREAD

**Issue by mhoibo** [mahmoodlab/CLAM#263]
Hi, 

Thank you for creating a great framework!

I have been looking into, and testing your framework for a binary classification problem. I have had some issues interpreting the models and determining which model is most promising in my use-case. 

As I understand it, 'clam_sb' should be the desired choice for a binary classification problem, however, the pure 'mil' model does not perform worse in my user case.  In the read-me there is no mention of the mil-model. Is the main difference between the 'clam_sb' and the 'mil' model that the mil does not have attention? Or is there something else important? Is there any user-case you can think of where the pure 'mil' model is favorable?

Thank you in advance!

**Comment by fedshyvana** [comment]
yes - mil just does standard non-parametric max-pooling (no attention). It can still perform well for problems like tumor detection, but empirically I found it to be less consistent across tasks, and struggles more in multiclass scenarios.
