### ISSUE TITLE
Identify tumor regions 

### ISSUE THREAD

**Issue by wangzhengxiao** [mahmoodlab/CLAM#264]
Hi，
     I am a beginner of pathology AI, and I want to  identify  tumor regions using attention scores.  Is there a easy way to achieve this?
Thanks a lot for your help!

**Comment by fedshyvana** [comment]
It's tricky to use attention scores to directly identify tumor regions - I suggest you checking out our more recent works like UNI (Figure 4.) and CONCH (Figure 2.), which showed that you can try to use prototypes (whether it's ROIs with known class labels or text prompts) to label regions in the slide without needing to train an ROI-level classifier.
