### ISSUE TITLE
Code is not reproducible with certain TCGA svs WSI

### ISSUE THREAD

**Issue by quincy-125** [mahmoodlab/CLAM#27]
I tested your code with TCGA-DA-A95X-01Z-00-DX1.F66442E6-F0C9-4528-B000-E47FCAA964FD
(breast histology BRAF mutated svs WSI downloaded from TCGA database)
you code was not able to be reproducible for this sample even on the data preprocessing part. 

I reported the issue here, many thanks!

**Comment by fedshyvana** [comment]
Hi Quincy, I do not believe there to be any issue with the code itself. I looked at TCGA-DA-A95X-01Z-00-DX1.F66442E6-F0C9-4528-B000-E47FCAA964FD, the tissue regions are small within the slide, so it's likely that its simply filtered out as artifacts under the default segmentation parameters. You can check the segmentation mask under "masks" to verify if this is the case. If you have slides like this in your dataset, you should set a smaller default "a_t" and "a_h" values or simply tweek the parameters for the select slides that are not segmented correctly (see README for more details on what the parameters do and how to adjust them).

**Comment by fedshyvana** [comment]
![TCGA-DA-A95X-01Z-00-DX1 F66442E6-F0C9-4528-B000-E47FCAA964FD](https://user-images.githubusercontent.com/39780468/104109495-82eedc80-529c-11eb-8e83-270b593b11a1.png)
Here's the stitched result for setting a_h and a_t as 1 for example.

**Comment by quincy-125** [comment]
Thanks for your quick response, that means we need to manually tweek the threshold, does this is the point you mean to say? If it is, I'm wondering to know if I have a large dataset, that means I have to manually adjust the threshold for samples like what I provided to you. Correct me if I'm wrong. Thanks so much!

**Comment by fedshyvana** [comment]
Yes, you can't go wrong with manually checking and changing parameters for select slides, but you can also define your own set of default segmentation values, and pass it to the "--preset" flag. For example, I think if you know that not every slide in your dataset contains large resected tissue, and instead you have biopsies and slides with small tissue fragments, I would just set define a preset with smaller a_t and a_h values. e.g. you can just take the tcga.csv preset file, and set a_t and a_h to be smaller (e.g. less < 10), and use that as your default values.

**Comment by quincy-125** [comment]
sure, that makes sense to me. I actually re-implemented your code in tensorflow, that's why I want to test your code just to make sure I got your logic of this model correctly. not sure you would like to help and see if my re-implemented version is the same as your idea? If it is, you could leave your email in below, I'll reach out to you offline. 

Anyway, thanks for your response again. you could close this issue now. Highly appreciated.

**Comment by fedshyvana** [comment]
Sure my email is mingyanglu1997@gmail.com. I am however not confident that I would be able to contribute much since I'm not familiar with Tensorflow syntax.
