### ISSUE TITLE
Specify masks?

### ISSUE THREAD

**Issue by mguzm4n** [mahmoodlab/CLAM#281]
Hey everyone! Is it possible to specify the mask for each slide for extracting patches? I wrote my own little program to crop my slides but it is too slow, and CLAM tool is really fast, but I got already detailed masks generated on my own that I'd like to use.

**Comment by BioCoderR** [comment]
Refer to this issue #104 where the author had issue where he wanted to use a segmentation from different masks like you. So this was solved and updated the code line you can refer to: https://github.com/KarthikNair1/CLAM/blob/314cda7bafc68bf26394e6ad4fadd0b859d860dd/wsi_core/WholeSlideImage.py#L419
