### ISSUE TITLE
Format of h5 files

### ISSUE THREAD

**Issue by samkleeman1** [mahmoodlab/CLAM#29]
Hi Sam, sorry I am not totally clear about your question, are you saying you already have the tiles (presumably stored in some standard image format like .jpg or .png) and are wondering how you might generate h5/pt files used as inputs to training a model? 
Max

_Originally posted by @fedshyvana in https://github.com/mahmoodlab/CLAM/issues/22#issuecomment-733254901_

My apologies for the delay in answering this, I had not seen your response. Yes your question is correct, I have already generated the tiles for my cohort in JPG format, and I am wondering how to use these as input. This is necessary as the slide images and the annotations are in pretty strange formats at present.

**Comment by fedshyvana** [comment]
Hi Sam, i responded in the original post. 
Best,
Max
