### ISSUE TITLE
PAIP 2019 datasets

### ISSUE THREAD

**Issue by codingcode111** [mahmoodlab/CLAM#33]
Hi, 
Is it possible to use your work on PAIP 2019 Liver cancer Segmentation Challenge datasets. This challenge is a regional segmentation https://paip2019.grand-challenge.org/Dataset/  we need first to generate patches and classify wether the patches (viable or whole) based on the ROI for viable for each slide, which has been provided in the csv file, and then we do the segmentation task. If you think your work can be used on my datasets, can you kindly explain how and provide more details, I’m new to this task and your reply and suggestion would be highly appreciated.  

best regards

**Comment by fedshyvana** [comment]
Hi, the repository is meant for weakly-supervised classification (without detailed patch-level annotations) therefore I don't think it's the right tool for the challenge.
