### ISSUE TITLE
Can this project be extended to more than 3 class classification?

### ISSUE THREAD

**Issue by Amith1503** [mahmoodlab/CLAM#35]
Thanks for making this repo public. I went through the paper, it was an impressive work. Can you please guide me if this set up can be extended to multi class classification with more than 3 labels.

**Comment by fedshyvana** [comment]
Yes, you can refer to the example provided for 3-class classification (tcga_kidney_cv) example in main.py. Using more classes is analogous - just have to setup your dataset object accordingly so that label dictionary specifies the entire set of classes, and set args.n_classes accordingly.

**Comment by Amith1503** [comment]
Thanks for the response. The reply was helpful. It would be great if you could answer one more query of mine. 

* In the "dataset_csv/tcga_kidney_clean.csv" there are a total of 891 records whereas in the splits folder "split/tcga_kidney_cv_50" each of the split.csv after a 50% split contains train-349 ,val-89 and test-85 which sums up to 523 out of 891 initial record. Can you please clarify if this is done on purpose of not using the entire dataset for train/val/test split, it would also be very helpful if the intuition behind this is mentioned.

Thanks in advance.

**Comment by fedshyvana** [comment]
I used 50% of the dataset for demonstration purposes in the README - in the paper I evaluate the algorithm using different proportions of the dataset for training. You'e free to use partition your dataset however you want. You are also not obligatory to use the script I provided to dataset partitioning - the splits have a very simple format of having 3 columns of slide-ids corresponding the training/val/test set. You can look at the examples under the splits folder.

**Comment by Amith1503** [comment]
Thank you.

**Comment by Amith1503** [comment]
Thanks for the help
