### ISSUE TITLE
Graceful failure 

### ISSUE THREAD

**Issue by surya-narayanan** [mahmoodlab/CLAM#37]
Hi, 

When creating patches for one of my svs files, I think the h5 file creation failed for one of my svs files (Not sure why) and as a result, the entire program halted. Would it be possible to catch errors gracefully?

**Comment by fedshyvana** [comment]
Hi, yes, we're planning on rolling out qol changes in upcoming iterations. for now if you have issues with specific topics (e.g. failure of h5 creation for particular slide) feel free to let me know the commands you ran and post the error log and I can help take a look.

**Comment by surya-narayanan** [comment]
Here is the code I am running

`python create_patches.py --source /mnt/disks/data_disk/LUAD/LUAD_healthy --save_dir /mnt/disks/data_disk/LUAD/LUAD_healthy_CLAMs --patch_size 256 --preset tcga.csv --seg --patch --stitch
`

Here is my error log. 

```
progress: 0.44, 107/242
processing TCGA-49-AAR3-11A-01-TSA.A2FB7679-FB9F-4E80-855F-77877C694D26.svs
Creating patches for:  TCGA-49-AAR3-11A-01-TSA.A2FB7679-FB9F-4E80-855F-77877C694D26 ...
Traceback (most recent call last):
  File "create_patches.py", line 294, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "create_patches.py", line 188, in seg_and_patch
    heatmap, stitch_time_elapsed = stitching(file_path, downscale=64)
  File "create_patches.py", line 14, in stitching
    heatmap = StitchPatches(file_path, downscale=downscale, bg_color=(0,0,0), alpha=-1, draw_grid=False)
  File "/mnt/disks/data_disk/CLAM/wsi_core/WholeSlideImage.py", line 46, in StitchPatches
    file = h5py.File(hdf5_file_path, 'r')
  File "/opt/conda/envs/clam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/conda/envs/clam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/mnt/disks/data_disk/LUAD/LUAD_healthy_CLAMs/patches/TCGA-49-AAR3-11A-01-TSA.A2FB7679-FB9F-4E80-855F-77877C694D26.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by fedshyvana** [comment]
Hi, if the error is that the script can't find the .h5 file, the likely cause is that the segmentation did not produce any image patches for that slide - you might want to double check the segmentation result for that particular slide in the masks folder and adjust the segmentation accordingly if necessary.
