### ISSUE TITLE
Requesting requirements.txt file for virtualenv users

### ISSUE THREAD

**Issue by mayurmallya** [mahmoodlab/CLAM#38]
Hi,

Could you please share a requirements.txt file for the venv users? 

You can run the following command from within the 'clam' conda env-
`pip freeze > requirements.txt`

Ref- https://stackoverflow.com/questions/48787250/set-up-virtualenv-using-a-requirements-txt-generated-by-conda

Thank you.

**Comment by fedshyvana** [comment]
[requirements.txt](https://github.com/mahmoodlab/CLAM/files/6000315/requirements.txt)
Feel free to see if this works for the time being - I believe it has some extra packages that are not required. I will update it once I do a more thorough test.

**Comment by scjjb** [comment]
Hi, was this requirements file ever reduced down? 

I'm trying to get CLAM running in Docker so I can utilise multiprocessing on my Windows desktop

**Comment by mayurmallya** [comment]
Hi, I don't think they updated the requirements file but the one attached above works well for me. However I'm not working on the datasets they used, so can't comment on the reproducibility.
