### ISSUE TITLE
Executing the whole pipeline on a new dataset

### ISSUE THREAD

**Issue by zaid478** [mahmoodlab/CLAM#4]
I was wondering if I can train CLAM on a new dataset. Currently, I have [this](https://figshare.com/articles/BreCaHAD_A_Dataset_for_Breast_Cancer_Histopathological_Annotation_and_Diagnosis/7379186) dataset and I have placed it in the directory. Can you guide me on how to do this? create_patches.py is accepting the directory but it is creating empty folders for patches. Can you guide me where i am going wrong. The image size is of 1360x1024

I would be grateful for your response.

**Comment by fedshyvana** [comment]
Hi Muhammad, I see you have closed the issue. Should you have further problems, feel free to make a new post to the forum.
