### ISSUE TITLE
Visualizing attention scores?

### ISSUE THREAD

**Issue by slee7268** [mahmoodlab/CLAM#40]
Is the code to visualize the attention scores on the patches available?

**Comment by fedshyvana** [comment]
Hi, heatmap visualization is handled through the **visHeatmap** function of the **WholeSlideImage** class. Once you construct a WSI object, and compute attention scores, you can pass the attention scores, coordinates, along with other arguments (see **visHeatmap** definition for details) to build a heatmap. In the future we might provide a comprehensive streamlined example for how this can be done for an arbitrary dataset, but for now the pieces are there for you to implement your own script if necessary.
