### ISSUE TITLE
Segmentation parameter recommendations for immunohistochemical stained WSI

### ISSUE THREAD

**Issue by gabemarx** [mahmoodlab/CLAM#43]
Hello,
I am working with WSI of human hippocampal tissue stained with AT8 IHC to detect neurofibrillary tangles. The ICH creates a dark brown stain for positive tissue while the negative tissue is quite light. When running CLAM on cases with a great deal of positive stain, I am unable to get segmentation of the negatively stained tissue. I have played with combinations of parameters but have not been successful at getting adequate tissue coverage. 
Would love any recommendations for better segmentation performance. 

Best,
Gabe

**Comment by Tejussurendran** [comment]
@gabemarx I am also running trying to work with a similar set of tissue with AT8 staining, and I was wondering if you ever found a good set of parameters for segmentation
