### ISSUE TITLE
saving coords without images?

### ISSUE THREAD

**Issue by gabemarx** [mahmoodlab/CLAM#44]
Hello! 

Thank you for the great repo! 

I was wondering if you recommend a way to save the patches file with just the coords. I am only using the coordinates for my project and the images take up too much memory. 

Thanks so much!
Gabe

**Comment by fedshyvana** [comment]
yes - the new fast patching pipeline that i updated on March 1st only saves coords, which saves storage but also is much faster if you don't need to save images.

**Comment by gabemarx** [comment]
great! how do I access that?

**Comment by fedshyvana** [comment]
It’s already on updated on github, you just have to download/pull the
latest version.
