### ISSUE TITLE
How to extract tissue patches as .jpg files

### ISSUE THREAD

**Issue by hesiqi1998** [mahmoodlab/CLAM#45]
Thanks for sharing this great repository, it works really well! I was wondering if you could provide some guidelines how to extract save tissue patches as pictures instead of h5 files?

**Comment by fedshyvana** [comment]
are you using the create_patches_fp.py or create_patches.py? If you use create_patches_fp.py, coordinates of segmented and extracted tissue patches are saved in an array, you can then write a simple script to loop through them to extract the regions corresponding these coordinates from your slides and save as .jpeg.

**Comment by bryanwong17** [comment]
Hi @hesiqi1998 could you provide guidelines on what should be added to extract tissue patches as .jpg files? Thank you!
