### ISSUE TITLE
Need help in understanding the clustering step

### ISSUE THREAD

**Issue by SamanvithKaranth** [mahmoodlab/CLAM#49]
Thanks for such an amazing work!!!

I'm working on a 3-class molecular subtyping task. I've used single-attention-branch CLAM model.

I'm not very clear on the clustering step. For a 3-class subtype, my understanding is that positive/negative class clusters are computed for each of the 3 classes. Am I understanding it correctly? 
When training the model, I see print statements only for class 0 & class 1 clustering accuracy. Another point to note is that class 0 clustering accuracy is ~ 100% and class 1 clustering accuracy is ~ 0%

**Comment by fedshyvana** [comment]
hi, i agree the print statements are a little confusing, your understanding is correct regarding positive/negative class for each of 3 classes. The "class 0" and "class 1" are referring to all the examples that should belong to the "negative" and "positive" cluster respectively, regardless of what the slide-level label is. 

From my experience the accuracy number typically starts out that way and pick up and becomes meaningful for both classes at some point over the course of training. Keep in mind the accuracy is "arbitrary" in that it just uses the 0.5 cutoff on predicted scores to binarize the scores to 0 (negative) and 1 (positive) so even if the accuracy score is not improving, the decision boundary of the model is changing and so monitoring the loss is probably more informative to see if the task is improving or not.

**Comment by SamanvithKaranth** [comment]
Understood! Thanks you so much!

**Comment by SamanvithKaranth** [comment]
One more question, I understand that positive/negative clusters are for each of the 3 classes but how do we get the total no. of true positive/negative clusters (as shown in output below, where true class 0 cluster  are 10,728 and true class 1 clusters are 3,576)

![github1](https://user-images.githubusercontent.com/35607751/115824405-7d6d6a80-a425-11eb-9303-fd8f709f8d0a.png)

**Comment by fedshyvana** [comment]
It depends on whether you have the mutual exclusive assumption (enabled via --subtyping) or not and your choice of --B With --subtyping, for each slide, top B patches are chosen to be the positive cluster of the true class, and negative cluster of the remaining classes. While the bottom B patches are chosen to be the negative cluster of the true class. If --subtyping is not enabled, then simply for each slide, top B patches are chosen to be the positive cluster of the true class, and the bottom B patches are chosen to be the negative cluster of the true class.
