### ISSUE TITLE
Conda installation issues

### ISSUE THREAD

**Issue by tmabraham** [mahmoodlab/CLAM#5]
Thanks for providing us great open-source code for us to use. I can't wait to try it out!

There are two installation issues I have noted:

1. Conda spends 5-10 minutes "Solving environment". There _may_ be some issue here (see [this message](https://github.com/conda/conda/issues/7690#issuecomment-472280902) but I am not too familiar with the conda install process and the channels used to be able to propose a solution unfortunately.

2. There is some clash in the setuptools version and openslide-python. If I try to install as is, I get [this error](https://github.com/openslide/openslide/issues/287). If I set the setuptools in `clam.yaml` to v45.3.0, then this error is resolved and it seems like the requirements are successfully installed...

**Comment by fedshyvana** [comment]
Hi Tanishq, I do not think I know enough about Conda installation to identify a proper solution either. When I tested installation on my workstation (Ubuntu 18.04) just now I was not able to reproduce the error. Just to clarify, you were able to successfully install everything after changing setuptools in the .yaml to v45.3.0?

**Comment by tmabraham** [comment]
@fedshyvana Yes that is true... Surprising you were unable to replicate the error. I just followed the same instructions as was written in the installation guide. With the change in setuptools version, I was able to follow through the entire installation guide.

**Comment by tmabraham** [comment]
Just wanted to note that I also tried installation on my personal laptop (the previous attempt was on a university server) and had the same setuptools issue which was fixed with the downgraded setuptools version.

**Comment by fedshyvana** [comment]
Got it thanks! Good to know that you're able to install after the tweak. After looking at the issue you linked, it appears outdated code from openslide-python might be the culprit. Let's keep the issue open for the time being, later this week I'll try downgrading setuptools on my workstation and other workstations in the lab to test the installation process and update the .yaml.
