### ISSUE TITLE
What script to use to rebuild the output image

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [mahmoodlab/CLAM#50]
Hi,

thanks for the great work. can you tell how was the visualization slide created.

**Comment by fedshyvana** [comment]
Hi, heatmap visualization is handled through the **visHeatmap** function of the **WholeSlideImage** class under **wsi_core**. Once you construct a WSI object, and compute attention scores (you can do this by simply passing the feature vectors for a given slide to a trained model and collecting the outputs), you can pass the attention scores, coordinates, along with other arguments (see visHeatmap definition for details) to build a heatmap. When I have time I will provide a comprehensive streamlined example for how this can be done for an arbitrary dataset, but for now the pieces are there for you to implement your own script if necessary.
