### ISSUE TITLE
Loading pre-trained models

### ISSUE THREAD

**Issue by tienn2** [mahmoodlab/CLAM#54]
Hi, thanks for making this all public! It's very impressive work. I have a bit of trouble loading the pre-trained models. For example, I tried loading the CLAM model trained on CAMELYON dataset.

My attempt looks like the following:
```
import torch
import sys
sys.path.append('./../CLAM/models')
from models import model_clam

model = model_clam.CLAM_MB()
checkpoint = torch.load('./../CLAM MIL Model Checkpoints/camelyon_40x_cv/camelyon_40x_cv_CLAM_50_s1/s_0_checkpoint.pt')
model.load_state_dict(checkpoint)
```

Then I get the following error:

> RuntimeError: Error(s) in loading state_dict for CLAM_MB:
	Missing key(s) in state_dict: "attention_net.0.weight", "attention_net.0.bias", "attention_net.2.attention_a.0.weight", "attention_net.2.attention_a.0.bias", "attention_net.2.attention_b.0.weight", "attention_net.2.attention_b.0.bias", "attention_net.2.attention_c.weight", "attention_net.2.attention_c.bias". 
	Unexpected key(s) in state_dict: "attention_net.module.0.weight", "attention_net.module.0.bias", "attention_net.module.3.attention_a.0.weight", "attention_net.module.3.attention_a.0.bias", "attention_net.module.3.attention_b.0.weight", "attention_net.module.3.attention_b.0.bias", "attention_net.module.3.attention_c.weight", "attention_net.module.3.attention_c.bias", "instance_loss_fn.labels". 

It seems the keys given to the model do not match with those expected. I'm relatively new with PyTorch. Do you have an idea why that is? Any help is appreciated, thanks!

**Comment by fedshyvana** [comment]
hi, there's been some naming changes since the time my model checkpoints were trained to when the code was cleaned up and released - if you look in the eval script, i had to update some key names in the state_dict for this to load properly. To save you trouble, here's an example if you want to do it outside of the eval script that i provided:

```
def clean_keys(ckpt):
    ckpt_clean = {}
    for key in ckpt.keys():
        if 'instance_loss_fn' in key:
            continue
        ckpt_clean.update({key.replace('.module', ''):ckpt[key]})
    return ckpt_clean
```

```
model = model_clam.CLAM_MB(dropout=True)
checkpoint = torch.load('CHECKPOINT_NAME.pt')
checkpoint = clean_keys(checkpoint)
model.load_state_dict(checkpoint, strict=True)
```

**Comment by tienn2** [comment]
Thank you! That fixed it.
