### ISSUE TITLE
Camelyon17 and Camelyon16 Training Data

### ISSUE THREAD

**Issue by Ajaz-Ahmad** [mahmoodlab/CLAM#55]
Hi,

I have seen the CLAM was trained and Evaluated over Camelyon16 and 17 challenge. Can you give more insight on how the data was combined, what was the number of ITC, Macro, Micro and Negative in train and test split.
Thank you.

Kind Regards
Ajaz Ahmad

**Comment by fedshyvana** [comment]
Hi, sorry for the delay I have been really busy with other projects. I believe what you're asking relates to https://github.com/mahmoodlab/CLAM/issues/52. You can refer to my responses there.
