### ISSUE TITLE
Heatmap greyscale issue

### ISSUE THREAD

**Issue by andymckenzie** [mahmoodlab/CLAM#60]
Hello and thank you for making this extremely helpful method.

I am trying to use your code to generate attention heatmaps. I have noticed that the generated images have a rectangular part of the image blocked off as greyscale. I would like to get rid of this. I'm not sure if this is a parameter that can be adjusted in the .yaml file or if something else is causing it. Could you please provide any guidance on how to address this issue? 

<img width="133" alt="greyscale_clam" src="https://user-images.githubusercontent.com/1280394/120650680-05df2200-c44c-11eb-9d6d-18ecd8b33f1d.png">

**Comment by fedshyvana** [comment]
i believe this is a known bug of certain version of the pixman library used by openslide so it's not something that you can do to fix in CLAM or python. See the last section of https://github.com/mahmoodlab/CLAM/blob/master/docs/INSTALLATION.md for the issue and https://github.com/mahmoodlab/CLAM/issues/13 for discussion and possible solutions.
