### ISSUE TITLE
ROC curves in paper

### ISSUE THREAD

**Issue by yyyzzzhao** [mahmoodlab/CLAM#65]
**Thanks for your great work! 

The figures in your paper are so elegant. Can you tell me how to plot the ROC curves like these displayed in your paper?

Much appreciation to see your reply!**

**Comment by fedshyvana** [comment]
You can refer to some sample code [here](https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc_crossval.html) and [here](https://scikit-learn.org/stable/auto_examples/model_selection/plot_roc.html). For labeling axes/legend the font used is Helvetica.

**Comment by yyyzzzhao** [comment]
thank you so much, i will learn these  code samples.
