### ISSUE TITLE
Custom default segmentation visualization parameter, vis_level

### ISSUE THREAD

**Issue by Hokiee** [mahmoodlab/CLAM#67]
Hello Max, I tried to adjust the downsample level to visualize the segmentation results by assigning a positive integer (e.g., 3) to the segmentation visualization parameter, `vis_level`. I got the following `IndexError`.

```
{'seg_params': {'seg_level': -1, 'sthresh': 15, 'mthresh': 11, 'close': 2, 'use_otsu': False, 'keep_ids': 'none', 'exclude_ids': 'none'}, 'filter_params': {'a_t': 1, 'a_h': 1, 'max_n_holes': 2}, 'patch_params': {'use_padding': True, 'contour_fn': 'four_pt'}, 'vis_params': {'vis_level': 3, 'line_thickness': 50}}
...
Traceback (most recent call last):
  File "create_patches_fp.py", line 307, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "create_patches_fp.py", line 188, in seg_and_patch
    mask = WSI_object.visWSI(**current_vis_params)
  File "/gpfs/gsfs12/users/lup2/CLAM/wsi_core/WholeSlideImage.py", line 187, in visWSI
    downsample = self.level_downsamples[vis_level]
IndexError: list index out of range
```

Could you please advise how to fix it? If I'd like to use the downsample in the WSI closest to 128x downsample level to visualize the segmentation results, should I assign 128 to `vis_level`? Thanks.

**Comment by fedshyvana** [comment]
Hello, each WSI has a set of predefined downsample levels, which are indexed by **vis_level**. If you get an index out of range error for using 3 it just means there's in total < 4 downsample levels in total. If you want to use level closest  to 128x downsample, you can change line 147 of create_patches_fp.py:

```python
best_level = wsi.get_best_level_for_downsample(64)
```
i.e. change 64 to 128.

**Comment by Hokiee** [comment]
Understood. Thanks.
