### ISSUE TITLE
Feature extraction speed problem.

### ISSUE THREAD

**Issue by YohnGuan** [mahmoodlab/CLAM#69]
Hi, I encountered a problem that the feature extraction is quite slow and it may take ~10 days to extract 1000 WSIs.
I am using TCGA as dataset. 

Do you have the save speed problem?

Thanks!

**Comment by fedshyvana** [comment]
Hi, the speed is largely going to depend on 1. area of tissue content and number of tiles (e.g. 20x vs 40x, how much of slide is actually tissue, tile size, etc.) and 2. number of GPUs. 

When you say feature extraction are you referring to just running either extract_features_fp.py/extract_features.py or also including create_patches.py and create_patches_fp.py? 

Are you using the _fp pipeline or the non _fp pipeline?

**Comment by YohnGuan** [comment]
Thans for your reply!
I am using the new pipeline according to Readme.md, the feature extraction I mean is runing only extract_features_fp.py (btw runing create_patches_fp.py is fast). 
I think the reseaon of low speed during feature extraction is because the patch reading procedure, increasing `num_worker` in dataloader or dividing dataset into independent parts and running parallel will help.

**Comment by johnchen99** [comment]
> I also encounter speed problem in my project. And there is something strange that when i run this script <extract_features_fp.py> in different workstation equipped with different graphics (1. titan xp; 2. 3090; 3.2080), resources usage are different. In titan xp, the usage of cpu and gpu are low. In 3090 and 2080, the usage of gpu is low while the cpu is near to a full load. The process speed in 3 workstation is about the same with @YohnGuan

Hi @yyyzzzhao , may I know do you encounter package dependencies problems with the yaml when executing with 3090?
