### ISSUE TITLE
The "flaw" in stiches 

### ISSUE THREAD

**Issue by YohnGuan** [mahmoodlab/CLAM#71]
Sorry to bother, I found that there are some "flaw" in the result stiches when runing `create_patches_fp.py`  on TCGA dataset.
The example is as:
![TCGA-O2-A52N-01Z-00-DX1 FF1DD149-4DBE-44C7-872D-FA7E8FE770A8](https://user-images.githubusercontent.com/43492597/127622279-0670f477-0d24-49b4-8659-f1649745362d.jpg)
The corresponding mask is good:
![TCGA-O2-A52N-01Z-00-DX1 FF1DD149-4DBE-44C7-872D-FA7E8FE770A8](https://user-images.githubusercontent.com/43492597/127622354-06de1647-6863-4468-8e52-59de402f5c9e.jpg)

I wonder if this will influnce the final results, thx!

**Comment by fedshyvana** [comment]
I believe the same issue as https://github.com/mahmoodlab/CLAM/issues/60. You most likely have a bugged version of the pixman library. Updating it should solve the problem.

**Comment by YohnGuan** [comment]
thx! Problem solved by your [solution](https://github.com/mahmoodlab/CLAM/issues/13#issuecomment-690302714).
