### ISSUE TITLE
Patching on microscopy images

### ISSUE THREAD

**Issue by tienn2** [mahmoodlab/CLAM#72]
Hello, 

I'm trying to apply the CLAM pipeline on the microscopy images of the public BACH dataset: https://iciar2018-challenge.grand-challenge.org/Dataset/. Here are some examples of images in the dataset:
![image](https://user-images.githubusercontent.com/38996274/127712218-661c5137-6d85-4189-b25a-0cf7281245a6.png)

Since these are not WSI and don't have a background to segment from the tissue in the foreground, running the script create_patches_fp.py isn't generating patches: folders "patches" and "stitches" are empty, whereas the folder "masks" contains all the .jpg images for the whole dataset. The script runs completely without error but produces the following output:
![image](https://user-images.githubusercontent.com/38996274/127714870-4ebb2e74-c41b-4a47-b868-0a36fa664884.png)

I know CLAM was developed to be used on WSI but was curious to use it on microscopy images. I was wondering if you had a quick solution to generate the .h5 patches from these microscopy images (.tif format).

Thanks!

**Comment by fedshyvana** [comment]
it should in principle work fine - i suspect its just a matter of the algorithm not segmenting properly. I think it's probably an area thing - if you create a custom preset csv and set a_h to 0 it should work, and pass that to the script via --preset it would probably work.

**Comment by tienn2** [comment]
Thank you! I used a bwh_biopsy.csv preset file and it worked fine.
