### ISSUE TITLE
Too large for successful segmentation and aborted

### ISSUE THREAD

**Issue by wenlongming** [mahmoodlab/CLAM#78]
Hi,

Thanks for your wonderful work on WSI. 
I run 'python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --seg --patch --stitch', but something wrong happened.

eg:
JPEGPreDecode: Warning, Improper JPEG sampling factors 2,1
Apparently should be 2,2..
JPEGPreDecode: Warning, Decompressor will try reading with sampling 2,1..
level_dim 85760 x 1006008 is likely too large for successful segmentation, aborting

I want to know how to solve this problem and look forward to your reply.

**Comment by fedshyvana** [comment]
i think 85760 x 1006008 seems way too big to be viewed/processed directly? curious whether you have been able to successfully view/process that image at that resolution in any other software. Maybe try a lower downsample if its available?

**Comment by wenlongming** [comment]
sorry, it was 85760 x 100608. Image format is tiff, and i can view it directly in win10. 
can i set a lower downsample in CLAM? and how to set?
i feel a little confused about the seg_level, if seg_level =1 or 2 means what?

**Comment by fedshyvana** [comment]
seg_level is the downsample level to perform the segmentation - level 0 is the highest magnification (i.e. 85760 x 100,000), you can try levels 2,3, etc. if they exist. or maybe just set level to -1?
