### ISSUE TITLE
Patch filtering

### ISSUE THREAD

**Issue by micdic** [mahmoodlab/CLAM#80]
HI there. Great project indeed.

We are trying to classify subtypes of a certain type of tumor. Our dataset (weakly labeled at the slide level),
presents some WSi areas with some noise (i.e. blurring). 
If i want to add some filtering capabilities (at a level patch) to the CLAM pipeline, i guees i need to manage the .ht5 files,
i.e. extracting each patch from coords data, apply a filter to the patch, and eventually remove the specific coords from the data inside the .h5 file. It's correct ? or there is a better possible approach?
Thanks.

**Comment by fedshyvana** [comment]
Hi,
Yes, unfortunately I do agree with your assessment that this might be easiest way to go about it without digging too much into changing the actual code.

But if you have a large dataset and are worried about introducing too much extra computational overhead you could consider implementing a filter function in the feature extraction script since that is when the image patches are actually loaded in using the coordinates in the h5 file.

**Comment by micdic** [comment]
Thanks for your answer. I'll start coding some possible filters (es. blurred images) and try to integrate them in the features extraction script (sharing the results).

**Comment by micdic** [comment]
Hi Max.
I've integrated a couple of filtering functions in the feature extraction with OpenCV code, de-normalizing the tensors coming from PyTorch. Now results seems to be improving (i'm trying to classify 3 cancer subtypes). My questions is now related to the AUC and ACC scores. In some models (out of 10 by default provided) it happens that a good AUC score (around 9.0) corresponds to a lower accuracy (i.e 7.0) (both for test and validation). Can this be related to the positive/negative clustering evaluation? I guess (not really sure) that the classifier achieves a good performance on positive class but lower values for negative class.

If i see the log , i found very often something like (sample row values, but proportionally always with this difference) :
negative=0 / positive=1 class 0 clustering acc 0.9837962962962963: correct 2975/3024
negative=0 / positive=1 class 1 clustering acc 0.3521825396825397: correct 355/1008

Can you please provide some details about the relationhip between clustering acc and overall evaluation?
Thanks really in advance.
