### ISSUE TITLE
segmentation results of TCGA data

### ISSUE THREAD

**Issue by JunMa11** [mahmoodlab/CLAM#83]
Hi @faisalml ,

Thanks for sharing the great work.

Would it be possible for you to share the segmentation masks of the TCGA pathology data?

**Comment by fedshyvana** [comment]
Hi, the original segmentation masks were prepared using a much older version of the CLAM repo (before it was re-organized and made public) so they are not compatible with the current workflow. However, you should be able to get basically comparable segmentation results using the default parameters included in 'tcga.csv' (which is in fact what we used for later projects, although for some TCGA cohorts/slides with smaller tissue content, it would be helpful to lower a_h and a_t accordingly to e.g. <10).

**Comment by JunMa11** [comment]
Hi @fedshyvana 

Thanks for your reply very much. 

Could you share a download to these segmentation results? or send it to my email (junma11@foxmail.com)
