### ISSUE TITLE
patch black box problem.

### ISSUE THREAD

**Issue by Cook-AI** [mahmoodlab/CLAM#84]
Thank you for open-sourcing the code of the paper. 

I want to make a model using TCGA. However, When i make patch, block box is made. So a lot of image patches is disappeared.

![image](https://user-images.githubusercontent.com/60030735/141704660-13760c27-551b-4893-b7e8-4bdf9a6607a6.png)

**Comment by fedshyvana** [comment]
I think this is due to the issue described at the bottom of https://github.com/mahmoodlab/CLAM/blob/master/docs/INSTALLATION.md. 
Should be solved if you upgrade your pixman library.

**Comment by fedshyvana** [comment]
Also see here: https://github.com/mahmoodlab/CLAM/issues/13. I think pixman has been updated in conda so you can try https://anaconda.org/anaconda/pixman.

**Comment by Cook-AI** [comment]
Thank you for fast response.
