### ISSUE TITLE
Using the Pipeline on MRXS format Whole Slide Images

### ISSUE THREAD

**Issue by tarquo23** [mahmoodlab/CLAM#86]
Hi,
I am trying to use your framework on a dataset that I am trying to work on in my research work. The Whole Slide Images are generated in .mrxs format (unfortunately it's a costraint that I can't change), which is supported by openslide. Despite this, if I try to create patches with your code, both the image inside stitches and the one in mask, are extremely dirty and with a lot of noise inside not present in the original image. I attach an image as an example.

![sample](https://user-images.githubusercontent.com/32510884/143262426-0f2a8f8c-3d0c-463b-a5f4-6369e210d664.jpg)

Do you know if your code works only on svs images or have you tested it on other formats?
If so, do you have any idea if the applicability on mrxs format requires minimal changes or is it better to rewrite everything directly?
 
Thanks for your time

**Comment by fedshyvana** [comment]
mrxs shouldn't be an issue - this is likely due to a bug of outdated pixman library. See my responset to https://github.com/mahmoodlab/CLAM/issues/84

**Comment by tarquo23** [comment]
Yes i solved after some problems with pixman=0.40.
Thank you so much for your support!
