### ISSUE TITLE
cv2.error: OpenCV(4.5.4-dev) :-1: error: (-5:Bad argument) in function 'pointPolygonTest'

### ISSUE THREAD

**Issue by RuixiangZhao** [mahmoodlab/CLAM#89]
Thank you very much for sharing， it helps me a lot!
When I execute the "Basic, Fully Automated Run", it throws this error. How can I resolve this issue?

> progress: 0.00, 0/1
processing test_046.tif
Creating patches for:  test_046 ...
Total number of contours to process:  40
Bounding Box: 28224 83712 2177 2817
Contour Area: 2621440.0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ruixiang.zhao/miniconda3/envs/zrx/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ruixiang.zhao/miniconda3/envs/zrx/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/ruixiang.zhao/CLAM/wsi_core/WholeSlideImage.py", line 481, in process_coord_candidate
    if WholeSlideImage.isInContours(cont_check_fn, coord, contour_holes, ref_patch_size):
  File "/home/ruixiang.zhao/CLAM/wsi_core/WholeSlideImage.py", line 345, in isInContours
    if cont_check_fn(pt):
  File "/home/ruixiang.zhao/CLAM/wsi_core/util_classes.py", line 86, in __call__
    if cv2.pointPolygonTest(self.cont, points, False) >= 0:
cv2.error: OpenCV(4.5.4-dev) :-1: error: (-5:Bad argument) in function 'pointPolygonTest'
> Overload resolution failed:
>  - Can't parse 'pt'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt'. Sequence item with index 0 has a wrong type

**Comment by RuixiangZhao** [comment]
I have solved this problem, which is caused by the too high version of OpenCV. When I switch the version **from 4.5.4.58 to 4.1.2.30**, It can work normally！

All right, thank you for your sharing again!

**Comment by TumVink** [comment]
For the people who donot want to degrade their opencv version, add
 `        if isinstance(pt, (np.ndarray, np.generic)):

            pt = (int(pt[0]),int(pt[1]))` 
in the function `isInContours` in `WholeSlideImage.py`

Hope it helps!
Jingsong
