### ISSUE TITLE
difference among `seg_level`, `patch_level` and `custom_downsample`

### ISSUE THREAD

**Issue by RuixiangZhao** [mahmoodlab/CLAM#91]
What is the difference among `seg_level`, `patch_level` and `custom_downsample` these three parameters?
If I want to extract features of patches in **Camelyon16** at **20x magnification**, how should I set parameters?

**Comment by fedshyvana** [comment]
Hi, I'm taking a break from working on WSI data so unfortunately i don't have data at hand to figure out the exact values. But basically each WSI/slide has multiple levels of resolution: level 0, 1, 2, ... Level 0 is always the level with the highest resolution  whereas subsequent levels are successive downsamples of level 0. seg_level (level for segmentation), patch_level (level for patching) refer to these specific levels. 

For segmentation, I would just leave it at default (-1). For patch-level it would depend on what magnification you need. If I remember correct Camelyon is 40X at level 0 and 20X at level 1 so patch_level = 1 is presumably what you want. Custom_downsample additionally downsamples your patches - in this case you can just leave it at 1 (no additional downsampling).

**Comment by RuixiangZhao** [comment]
Thank you for your response, which answers my doubts.
