### ISSUE TITLE
Questions about RCC WSI dataset

### ISSUE THREAD

**Issue by pzSuen** [mahmoodlab/CLAM#92]
Hello,
I want to download the RCC WSI data from TCGA, but I encounter serval problems as follows.
![image](https://user-images.githubusercontent.com/43957007/147943059-94bc9c56-0f07-4bd7-b761-5fa7bffddc04.png)

Then I entered this page,
![image](https://user-images.githubusercontent.com/43957007/147943240-f836e400-2228-44bf-9041-ea8ba4a1ce2f.png)

And then, I found there is more than one slide for each case.
![image](https://user-images.githubusercontent.com/43957007/147943345-0c344645-cf07-4cdc-8a7e-8f892076d2e2.png)

But you said you get "489 CCRCC slides from 483 cases", 
so did I make mistakes while selecting the data?
And how do you choose the slide for each case?

**Comment by fedshyvana** [comment]
Hello, I downloaded the data towards end of 2019 - so its possible that changes have been made to the initial cohort. In any case, I basically go for: project_id = TCGA-KIRC, and select all diagnostic slides, which as you show in your picture, would be 519 slides from 513 cases atm. Some slides however, were discarded during preprocessing for quality control and technical considerations (e.g. I believe there's a few slides that only had 40x pyramid and no lower magnifications, and some had a lot of penmarkings, etc.) and were excluded some the study. 

For patients with multiple slides, each slide is treated as an independent sample but we make sure they stay grouped when partitioning the data into train/val/test (i.e. slides from the same patient do not get drawn into both train and val/test).

**Comment by pzSuen** [comment]
> 

Thank you~
So you clicked '519' to download rather than '513' as shown in the image?

![image](https://user-images.githubusercontent.com/43957007/147951374-a24feac0-f63b-48f5-9673-6fb0d477d451.png)

**Comment by fedshyvana** [comment]
I don't think there should be a difference? They are referring to the exact same data I believe. But the way I downloaded was through: [here](https://portal.gdc.cancer.gov/repository?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22content%22%3A%7B%22field%22%3A%22cases.project.project_id%22%2C%22value%22%3A%5B%22TCGA-KIRC%22%5D%7D%2C%22op%22%3A%22in%22%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22Diagnostic%20Slide%22%5D%7D%7D%5D%7D). Do **Add All Files to Cart** and then you can download a manifest file, and then use the gdc command-line tool to download them in bulk: [here](https://docs.gdc.cancer.gov/Data_Transfer_Tool/Users_Guide/Data_Download_and_Upload/)

**Comment by pzSuen** [comment]
Thank you very much!
