### ISSUE TITLE
(Old Issue #79) Patches and Stitches folder empty but images appear in masks

### ISSUE THREAD

**Issue by dgonzMD** [mahmoodlab/CLAM#93]
Hi, I'm having the same exact issues as the OP for this thread. Was this issue ever resolved?

I went through all the steps in that issue thread but the h5 files continue to be generated in the image directory. There are also no .pt files being generated. Masks appear to generate correctly.

This only seems to be happening to me on Windows. On Linux, I've gotten everything to work properly. The problem is that the PC in my lab runs on windows and I'm not allowed to run a Linux partition on it.

I've tried removing spaces from path names and changing everything to "/" instead of "\" in the path names but that actually made things worse.

Thanks!

**Comment by fedshyvana** [comment]
I unfortunately do not have access to a windows environment for testing but would be great if you could figure it out/if others  on windows had the same issue and were able to solve it.  link to the old issue referenced by op: https://github.com/mahmoodlab/CLAM/issues/79

**Comment by omniaalwazzan** [comment]
you can solve this issue by creating a folder DATA_DIRECTORY under the folder patches so your path containing the slide_1.h5 should look like that  \RESULTS_DIRECTORY\patches\DATA_DIRECTORY\slide_1.h5
