### ISSUE TITLE
extracting ROIs and preprocessing WSI image for graph neural network

### ISSUE THREAD

**Issue by liuxiaoping2020** [mahmoodlab/CLAM#96]
Firstly, I should thank mahmoodlab @faisalml  and Dr.  @fedshyvana  for their great work in this area. 
I just learning CLAM to preprocessing TCGA WSI svs files, and I have now utlized CLAM to:
 (1) create patches using via Ostu method, which generated masks, stitches, and patches:
`CUDA_VISIBLE_DEVICES=0,1 python create_patches_fp.py --source /mnt1/TCGA/data --save_dir /mnt1/TCGA/ostu_result --patch_size 256 --preset tcga_ostu.csv --seg --patch `--stitch`

(2) extracted features based on the h5 files generated above, which created pt files for subsequent analysis:
`CUDA_VISIBLE_DEVICES=0,1 python extract_features_fp.py --data_h5_dir /mnt1/TCGA/ostu_result --data_slide_dir /mnt1/TCGA/data --csv_path  /mnt1/TCGA/ostu_result/process_list_autogen.csv --feat_dir /mnt1/TCGA/ostu_result --batch_size 512 --slide_ext .svs`

The above analysis pipeline created h5 files and pt files, and I know the CLAM can be used to analyze normal vs tumor task and multiple subtype task.
However, I wonder whether the CLAM can be used to extract region of interest (ROI) and save it as common format (.png, jpg, etc.)? Can you guide me how to do this using CLAM? are there any pipelines/modules/examples that can take advantage of CLAM to finish this?

Secondly, I wonder whether CLAM can be used to preprocess WSI, and then construct graphs and dataset objects for graph neural network analysis? Can you guide me with some pipelines/modules/examples to do this?

Sincerely thanks and best regards

Xiaoping Liu

**Comment by fedshyvana** [comment]
Hello, yes you can use the output of the WSI preprocessing pipeline in this repo to create knn graphs before passing them to gnns. I believe you already followed https://github.com/mahmoodlab/Patch-GCN/blob/master/WSI-Graph%20Construction.ipynb, but your issue appears to be with some missing files that's not pertaining to creating knn graphs itself. I will leave it to @Richarizardd to answer your question on the other repo. 

For getting ROI, you don't need CLAM per se - its a simple matter of getting the coordinates of the ROI you want and using openslide's read_region function to extract the corresponding image.

**Comment by liuxiaoping2020** [comment]
Thank you very much for your reply.

I am just a beginer for AI patholoy, I spent a lot of time to find a appropriate method to extract ROI of WSI image, your advice helped me immensely, I will try to learn the openslide program. 
Meanwhile, I have followed the instructions you suggested to construct image graph，and I am tring to learn the patch-GCN pipeline, I found it also not easy to learn and reproduce, I have posted my issue at Patch-GCN repo, hoping it could be solved,

Sincerely thanks to you
Xiaoping
