### ISSUE TITLE
OpenSlideError during feature extraction

### ISSUE THREAD

**Issue by Dikec** [mahmoodlab/CLAM#97]
Hello,

Thank you for Mahmood Lab, it's an excellente AI toolbox for image analysis in Pathology !

I would like to work with your TOAD tools, that's why I first use CLAM for the creation of the databases, especially the features extraction.

However, I can't create the database to use TOAD because I have an error when using CLAM.
When I run :

`CUDA_VISIBLE_DEVICES=0 python extract_features_fp.py -- data_h5_dir DIR_TO_COORDS --data_slide_dir DATA_DIRECTORY --csv_path CSV_FILE_NAME --feat_dir FEATURES_DIRECTORY --batch_size 512 --slide_ext .svs`

I get the following error : 

![error_LI](https://user-images.githubusercontent.com/36924737/151778485-ef5a51d2-9669-4e97-936a-d68a047fa630.jpg)

My database is currently composed of two WSI .svs files from two public databases given in the TOAD article. https://cancerimagingarchive.net/datascope/cptac/ and https://portal.gdc.cancer.gov/ .
I don't really understand where the error comes from and I was hoping you could help me.
In advance, thank you
Best regards

Dimitri MIKEC

**Comment by fedshyvana** [comment]
Hi, to be honest I have not seen this error before. two things:
1. do the masks/stitches look normal for this problematic slide?
2. is this the only (or few slides) that are problematic? or does this happen with every slide

**Comment by Dikec** [comment]
1. I think they look normal, for example : 
Mask : 
![C3L-00452-41](https://user-images.githubusercontent.com/36924737/151811085-5531b0aa-f5da-4a55-8fd8-befabbdcf062.jpg)
Stitche : 
![C3L-00452-41](https://user-images.githubusercontent.com/36924737/151811165-8ff849ee-b254-43b2-9103-9ca9dea1e9e2.jpg)

2. I only work with 2 slides from the two public databases and both give me the same error. 
Maybe I should try with other slides.

**Comment by fedshyvana** [comment]
sure, feel free to follow-up if the issue persists and i'll try to look into it

**Comment by Dikec** [comment]
Hello,
I tried with two new images and I get the same error.
Could it be that it comes from the Openslide version? 

```
>>> import openslides
>>> print(openslides.__version__)
3.0
```

```
>>> import openslide
>>> print(openslide.__version__)
1.1.1
```

**Comment by fedshyvana** [comment]
yeah i think you should try to re-install openslide https://openslide.org/download/. Latest is version 3.4.1

**Comment by Dikec** [comment]
I uninstalled openslide and reinstalled in the latest version found by anaconda

version 3.3

But it is not the version 3.4.1, it tells me that it does not exist. Should I do a manual installation ?

Because even with version 3.3 I still have the same error: 

openslide.lowlevel.OpenSlideError: Cannot read raw tile

When I do 

apt-get install openslide-tools

it tells me that version 3.4.1 is already installed.
I think I don't understand the difference between openslide-tools and openslide anymore...

**Comment by Dikec** [comment]
After uninstalling openslide-python and openslides on my conda environment, I reinstalled openslide-python (it is now in version 1.1.2).
However the reinstallation of Openslides I still have version 3.3 and not version 3.4.1.
I tried several times, updating anaconda, conda, and pip.

**Comment by fedshyvana** [comment]
https://anaconda.org/conda-forge/openslide it says here that you can install 3.4.1 directly with conda

**Comment by Dikec** [comment]
Hello,

I have a good news ! 

We have fix the error.
I have uninstalled Openslides and Openslide-python, update anaconda and install Openslide of conda, reinstall openslide-python, and now it's good !

Thank you very much for your reponse
