### ISSUE TITLE
Black foreground after `segment` and pixel garbled after `stitch` 

### ISSUE THREAD

**Issue by pzSuen** [mahmoodlab/CLAM#98]
I am trying to use the original code and parameters to preprocess the slides in CAMELYON17,
but I encounter this problem as seen in the picture.

As you can see, 
the first problem is that the tissue in the bottom of the segment mask is grey with a green segment boundary. 
The second problem is garbled after stitching, I don't know whether the pixel will be garbled when I compute the features.

![image](https://user-images.githubusercontent.com/43957007/152666370-aaaf155f-f15f-4a8c-809a-e1b1e9b77ab0.png)

Thank you very much!

**Comment by fedshyvana** [comment]
it's a pixman issue - try installing pixman 0.40 (https://anaconda.org/anaconda/pixman)

**Comment by pzSuen** [comment]
The problem is solved.
Thank you very much!
