### ISSUE TITLE
Openslides or openslide?

### ISSUE THREAD

**Issue by hhoeflin** [mahmoodlab/CLAM#99]
You are mentioning a dependency to "openslides (3.4.1)" in your dependencies. Do you mean "openslide"?

Openslides (https://pypi.org/project/openslides/) seems to be a "OpenSlides is a free, Web-based presentation and assembly system for managing and projecting agenda, motions, and elections of assemblies"

Thanks for clarifying.

**Comment by CarlosHernandezP** [comment]
They do mention both, openslide (1.1.1) and openslides (3.4.1) at the readme and (3.0) at `docs/clam.yaml` but those are the only two instances of "openslides" in the whole repository.

It might be used for the attention demo.

**Comment by hhoeflin** [comment]
Yes I thought so. I also noticed that 'openslides' is also part of the conda environment-yaml in a version (3.0). Probably also an error?
